SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALL_GOVS_ALLIANCES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ALL_GOVS_ALLIANCES](
	[GovernorID] [float] NOT NULL,
	[Alliance] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ALL_GOVS_ALLIANCES]') AND name = N'IX_ALL_GOVS_ALLIANCES_GovernorID')
CREATE NONCLUSTERED INDEX [IX_ALL_GOVS_ALLIANCES_GovernorID] ON [dbo].[ALL_GOVS_ALLIANCES]
(
	[GovernorID] ASC
)
INCLUDE([Alliance]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
