SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_TaskStatus]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SP_TaskStatus](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TaskName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Status] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[LastRunTime] [datetime] NULL,
	[LastRunCounter] [int] NULL,
	[DurationSeconds] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
