SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RSSASSISTDelta]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RSSASSISTDelta](
	[GovernorID] [float] NOT NULL,
	[DeltaOrder] [float] NOT NULL,
	[RSSASSISTDelta] [float] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RSSASSISTDelta]') AND name = N'IX_RSSASSISTDelta_DeltaOrder')
CREATE NONCLUSTERED INDEX [IX_RSSASSISTDelta_DeltaOrder] ON [dbo].[RSSASSISTDelta]
(
	[DeltaOrder] ASC
)
INCLUDE([GovernorID],[RSSASSISTDelta]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RSSASSISTDelta]') AND name = N'IX_RSSASSISTDelta_DeltaOrder_GovernorID')
CREATE NONCLUSTERED INDEX [IX_RSSASSISTDelta_DeltaOrder_GovernorID] ON [dbo].[RSSASSISTDelta]
(
	[DeltaOrder] ASC,
	[GovernorID] ASC
)
INCLUDE([RSSASSISTDelta]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
