SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[KVK_Details](
	[KVK_NO] [int] NOT NULL,
	[KVK_NAME] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[KVK_REGISTRATION_DATE] [date] NULL,
	[KVK_START_DATE] [date] NULL,
	[KVK_END_DATE] [date] NULL,
	[MATCHMAKING_SCAN] [int] NULL,
	[KVK_END_SCAN] [int] NULL,
	[CreatedAt] [datetime2](0) NOT NULL,
	[NEXT_KVK_NO] [int] NULL,
	[MATCHMAKING_START_DATE] [date] NULL,
	[FIGHTING_START_DATE] [date] NULL,
	[PASS4_START_SCAN] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[KVK_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND name = N'IX_KVK_Details_Dates')
CREATE NONCLUSTERED INDEX [IX_KVK_Details_Dates] ON [dbo].[KVK_Details]
(
	[KVK_START_DATE] ASC,
	[KVK_END_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND name = N'IX_KVK_Details_FightingStart')
CREATE NONCLUSTERED INDEX [IX_KVK_Details_FightingStart] ON [dbo].[KVK_Details]
(
	[FIGHTING_START_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND name = N'IX_KVK_Details_KVK_NO')
CREATE NONCLUSTERED INDEX [IX_KVK_Details_KVK_NO] ON [dbo].[KVK_Details]
(
	[KVK_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND name = N'IX_KVK_Details_KVKNO')
CREATE NONCLUSTERED INDEX [IX_KVK_Details_KVKNO] ON [dbo].[KVK_Details]
(
	[KVK_NO] ASC
)
INCLUDE([KVK_END_SCAN],[MATCHMAKING_START_DATE],[FIGHTING_START_DATE],[PASS4_START_SCAN]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND name = N'IX_KVK_Details_MatchmakingStart')
CREATE NONCLUSTERED INDEX [IX_KVK_Details_MatchmakingStart] ON [dbo].[KVK_Details]
(
	[MATCHMAKING_START_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KVK_Details]') AND name = N'IX_KVK_Details_Next')
CREATE NONCLUSTERED INDEX [IX_KVK_Details_Next] ON [dbo].[KVK_Details]
(
	[KVK_NO] ASC,
	[NEXT_KVK_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_KVK_Details_CreatedAt]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[KVK_Details] ADD  CONSTRAINT [DF_KVK_Details_CreatedAt]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
END

