SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RANGED_D6D]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RANGED_D6D](
	[GovernorID] [bigint] NOT NULL,
	[RangedPointsDelta6Months] [bigint] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RANGED_D6D]') AND name = N'IX_RANGED_D6D_GovernorID')
CREATE NONCLUSTERED INDEX [IX_RANGED_D6D_GovernorID] ON [dbo].[RANGED_D6D]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
