SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DASH]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DASH](
	[RANK] [float] NOT NULL,
	[KVK_RANK] [bigint] NULL,
	[Gov_ID] [float] NULL,
	[Governor_Name] [nvarchar](255) COLLATE Latin1_General_CI_AS NULL,
	[Starting Power] [float] NOT NULL,
	[T4_KILLS] [float] NULL,
	[T5_KILLS] [float] NULL,
	[T4&T5_Kills] [float] NULL,
	[Kill Target] [int] NULL,
	[% of Kill target] [float] NULL,
	[Deads] [float] NULL,
	[T4_Deads] [float] NULL,
	[T5_Deads] [float] NULL,
	[Dead_Target] [float] NULL,
	[% of Dead_Target] [float] NULL,
	[KVK_NO] [int] NULL,
	[Pass 4 Kills] [float] NULL,
	[Pass 6 Kills] [float] NULL,
	[Pass 7 Kills] [float] NULL,
	[Pass 8 Kills] [float] NULL,
	[POWER_DELTA] [float] NULL,
	[DKP_Score] [float] NULL,
	[DKP Target] [float] NULL,
	[% of DKP Target] [float] NULL,
	[HealedTroops] [bigint] NULL,
	[HealedTroopsDelta] [bigint] NULL,
	[KillPointsDelta] [float] NULL,
	[RangedPoints] [bigint] NULL,
	[KvKPlayed] [int] NULL,
	[MostKvKKill] [bigint] NULL,
	[MostKvKDead] [bigint] NULL,
	[MostKvKHeal] [bigint] NULL,
	[Acclaim] [bigint] NULL,
	[HighestAcclaim] [bigint] NULL,
	[AOOJoined] [bigint] NULL,
	[AOOWon] [int] NULL,
	[AOOAvgKill] [bigint] NULL,
	[AOOAvgDead] [bigint] NULL,
	[AOOAvgHeal] [bigint] NULL,
	[Starting KillPoints] [float] NULL,
	[Starting Deads] [float] NULL,
	[Starting T4&T5_KILLS] [float] NULL,
	[Helps] [float] NULL,
	[RSS_Assist] [float] NULL,
	[RSS_Gathered] [float] NULL,
	[Pass 4 Deads] [float] NULL,
	[Pass 6 Deads] [float] NULL,
	[Pass 7 Deads] [float] NULL,
	[Pass 8 Deads] [float] NULL,
	[Starting HealedTroops] [bigint] NULL,
	[Civilization] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[KILLS_OUTSIDE_KVK] [float] NULL,
	[DEADS_OUTSIDE_KVK] [float] NULL,
	[Zeroed] [bit] NULL,
	[HelpsDelta] [bigint] NULL,
	[RSS_Assist_Delta] [bigint] NULL,
	[RSS_Gathered_Delta] [bigint] NULL,
	[RangedPointsDelta] [bigint] NULL,
	[Max_PreKvk_Points] [bigint] NULL,
	[Max_HonorPoints] [bigint] NULL,
	[PreKvk_Rank] [bigint] NULL,
	[Honor_Rank] [bigint] NULL,
	[Deads_Delta] [bigint] NULL,
	[AutarchTimes] [bigint] NULL
) ON [PRIMARY]
END
