SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[K46]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[K46](
	[GovernorID] [float] NOT NULL,
	[T4_KILLS] [float] NOT NULL,
	[ScanDate] [datetime] NOT NULL,
	[RowAsc6] [bigint] NULL,
	[RowDesc6] [bigint] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[K46]') AND name = N'IX_K46_GovernorID')
CREATE NONCLUSTERED INDEX [IX_K46_GovernorID] ON [dbo].[K46]
(
	[GovernorID] ASC
)
INCLUDE([T4_KILLS],[RowAsc6],[RowDesc6]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
