SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HEALEDSUMMARY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[HEALEDSUMMARY](
	[GovernorID] [bigint] NOT NULL,
	[GovernorName] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PowerRank] [int] NULL,
	[HealedTroops] [bigint] NULL,
	[StartingHealed] [bigint] NULL,
	[OverallHealedDelta] [bigint] NULL,
	[HealedDelta12Months] [bigint] NULL,
	[HealedDelta6Months] [bigint] NULL,
	[HealedDelta3Months] [bigint] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[HEALEDSUMMARY]') AND name = N'IX_HEALEDSUMMARY_PowerRank')
CREATE NONCLUSTERED INDEX [IX_HEALEDSUMMARY_PowerRank] ON [dbo].[HEALEDSUMMARY]
(
	[PowerRank] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[HEALEDSUMMARY]') AND name = N'PK_HEALEDSUMMARY_Gov')
CREATE UNIQUE NONCLUSTERED INDEX [PK_HEALEDSUMMARY_Gov] ON [dbo].[HEALEDSUMMARY]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[HEALEDSUMMARY]') AND name = N'UX_HEALEDSUMMARY_GovernorID')
CREATE UNIQUE NONCLUSTERED INDEX [UX_HEALEDSUMMARY_GovernorID] ON [dbo].[HEALEDSUMMARY]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
