SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[KingdomScanData4](
	[PowerRank] [float] NOT NULL,
	[GovernorName] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[GovernorID] [float] NOT NULL,
	[Alliance] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[Power] [float] NOT NULL,
	[KillPoints] [float] NOT NULL,
	[Deads] [float] NOT NULL,
	[T1_Kills] [float] NOT NULL,
	[T2_Kills] [float] NOT NULL,
	[T3_Kills] [float] NOT NULL,
	[T4_Kills] [float] NOT NULL,
	[T5_Kills] [float] NOT NULL,
	[T4&T5_KILLS] [float] NULL,
	[TOTAL_KILLS] [float] NULL,
	[RSS_Gathered] [float] NULL,
	[RSSAssistance] [float] NOT NULL,
	[Helps] [float] NOT NULL,
	[ScanDate] [datetime] NOT NULL,
	[SCANORDER] [float] NOT NULL,
	[SCAN_UNO] [int] NOT NULL,
	[Troops Power] [float] NULL,
	[City Hall] [float] NULL,
	[Tech Power] [float] NULL,
	[Building Power] [float] NULL,
	[Commander Power] [float] NULL,
	[AsOfDate]  AS (CONVERT([date],[ScanDate])) PERSISTED,
	[HealedTroops] [bigint] NULL,
	[RangedPoints] [bigint] NULL,
	[Civilization] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[KvKPlayed] [int] NULL,
	[MostKvKKill] [bigint] NULL,
	[MostKvKDead] [bigint] NULL,
	[MostKvKHeal] [bigint] NULL,
	[Acclaim] [bigint] NULL,
	[HighestAcclaim] [bigint] NULL,
	[AOOJoined] [bigint] NULL,
	[AOOWon] [int] NULL,
	[AOOAvgKill] [bigint] NULL,
	[AOOAvgDead] [bigint] NULL,
	[AOOAvgHeal] [bigint] NULL,
	[AutarchTimes] [int] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'CIX_KS4_ScanOrder_Governor')
CREATE CLUSTERED INDEX [CIX_KS4_ScanOrder_Governor] ON [dbo].[KingdomScanData4]
(
	[SCANORDER] ASC,
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_kingdomscandata4_GovID_ScanOrder')
CREATE NONCLUSTERED INDEX [IX_kingdomscandata4_GovID_ScanOrder] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[SCANORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_kingdomscandata4_GovID_ScanOrder] ON [dbo].[KingdomScanData4] DISABLE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KingdomScanData4_ScanDate')
CREATE NONCLUSTERED INDEX [IX_KingdomScanData4_ScanDate] ON [dbo].[KingdomScanData4]
(
	[ScanDate] ASC
)
INCLUDE([GovernorID],[Deads],[SCANORDER]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_KingdomScanData4_ScanDate] ON [dbo].[KingdomScanData4] DISABLE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_kingdomscandata4_SCANORDER')
CREATE NONCLUSTERED INDEX [IX_kingdomscandata4_SCANORDER] ON [dbo].[KingdomScanData4]
(
	[SCANORDER] ASC
)
INCLUDE([GovernorID],[Power],[Deads],[T4_Kills],[T5_Kills],[T4&T5_KILLS],[RSS_Gathered],[RSSAssistance],[Helps]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_kingdomscandata4_SCANORDER] ON [dbo].[KingdomScanData4] DISABLE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_kingdomscandata4_ScanOrder_DESC')
CREATE NONCLUSTERED INDEX [IX_kingdomscandata4_ScanOrder_DESC] ON [dbo].[KingdomScanData4]
(
	[SCANORDER] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KingdomScanData4_Scanorder1')
CREATE NONCLUSTERED INDEX [IX_KingdomScanData4_Scanorder1] ON [dbo].[KingdomScanData4]
(
	[SCANORDER] ASC
)
INCLUDE([PowerRank],[GovernorName],[GovernorID],[Power]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_KingdomScanData4_Scanorder1] ON [dbo].[KingdomScanData4] DISABLE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KingdomsScanData4_SCANORDER')
CREATE NONCLUSTERED INDEX [IX_KingdomsScanData4_SCANORDER] ON [dbo].[KingdomScanData4]
(
	[SCANORDER] ASC
)
INCLUDE([PowerRank],[GovernorName],[GovernorID],[Deads]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_KingdomsScanData4_SCANORDER] ON [dbo].[KingdomScanData4] DISABLE
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KS4_AsOf_Governor')
CREATE NONCLUSTERED INDEX [IX_KS4_AsOf_Governor] ON [dbo].[KingdomScanData4]
(
	[AsOfDate] ASC,
	[GovernorID] ASC
)
INCLUDE([TOTAL_KILLS],[KillPoints],[Deads],[Helps],[RSS_Gathered],[RSSAssistance],[Power],[GovernorName]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KS4_Governor_ScanDate')
CREATE NONCLUSTERED INDEX [IX_KS4_Governor_ScanDate] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[ScanDate] ASC
)
INCLUDE([Power],[KillPoints],[T4&T5_KILLS],[Deads],[GovernorName]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KS4_Governor_ScanDate_ScanOrder')
CREATE NONCLUSTERED INDEX [IX_KS4_Governor_ScanDate_ScanOrder] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[ScanDate] ASC,
	[SCANORDER] ASC
)
INCLUDE([Deads],[GovernorName],[PowerRank]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KSD4_AsOfDate_DESC')
CREATE NONCLUSTERED INDEX [IX_KSD4_AsOfDate_DESC] ON [dbo].[KingdomScanData4]
(
	[AsOfDate] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_KSD4_AsOfDate_DESC] ON [dbo].[KingdomScanData4] DISABLE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KSD4_Gov_Scan')
CREATE NONCLUSTERED INDEX [IX_KSD4_Gov_Scan] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[SCANORDER] DESC
)
INCLUDE([GovernorName],[Alliance],[City Hall],[Power],[T4&T5_KILLS],[T4_Kills],[T5_Kills],[Deads],[RSS_Gathered],[Helps]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_KSD4_Gov_Scan] ON [dbo].[KingdomScanData4] DISABLE
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KSD4_Gov_ScanOrder')
CREATE NONCLUSTERED INDEX [IX_KSD4_Gov_ScanOrder] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[SCANORDER] ASC
)
INCLUDE([PowerRank],[ScanDate]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KSD4_Governor_AsOfDate_SCANORDER_DESC')
CREATE NONCLUSTERED INDEX [IX_KSD4_Governor_AsOfDate_SCANORDER_DESC] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[AsOfDate] ASC,
	[SCANORDER] DESC
)
INCLUDE([RSS_Gathered],[Helps],[GovernorName],[Alliance]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER INDEX [IX_KSD4_Governor_AsOfDate_SCANORDER_DESC] ON [dbo].[KingdomScanData4] DISABLE
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KingdomScanData4]') AND name = N'IX_KSD4_Governor_ScanOrder')
CREATE NONCLUSTERED INDEX [IX_KSD4_Governor_ScanOrder] ON [dbo].[KingdomScanData4]
(
	[GovernorID] ASC,
	[SCANORDER] DESC,
	[AsOfDate] DESC,
	[ScanDate] DESC
)
INCLUDE([GovernorName],[Alliance]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_KS4_SCAN_UNO]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[KingdomScanData4] ADD  CONSTRAINT [DF_KS4_SCAN_UNO]  DEFAULT (NEXT VALUE FOR [dbo].[KS4_UNO_SEQ]) FOR [SCAN_UNO]
END

