SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DEADSSUMMARY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DEADSSUMMARY](
	[GovernorID] [float] NOT NULL,
	[GovernorName] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[PowerRank] [float] NOT NULL,
	[DEADS] [float] NOT NULL,
	[StartingDEADS] [float] NULL,
	[OverallDEADSDelta] [float] NULL,
	[DEADSDelta12Months] [float] NULL,
	[DEADSDelta6Months] [float] NULL,
	[DEADSDelta3Months] [float] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DEADSSUMMARY]') AND name = N'IX_DEADSSUMMARY_PowerRank')
CREATE NONCLUSTERED INDEX [IX_DEADSSUMMARY_PowerRank] ON [dbo].[DEADSSUMMARY]
(
	[PowerRank] ASC
)
INCLUDE([DEADS],[StartingDEADS],[OverallDEADSDelta],[DEADSDelta12Months],[DEADSDelta6Months],[DEADSDelta3Months]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DEADSSUMMARY]') AND name = N'UX_DEADSSUMMARY_GovernorID')
CREATE UNIQUE NONCLUSTERED INDEX [UX_DEADSSUMMARY_GovernorID] ON [dbo].[DEADSSUMMARY]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
