SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KILL4SUMMARY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[KILL4SUMMARY](
	[GovernorID] [float] NOT NULL,
	[GovernorName] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[POWERRank] [float] NOT NULL,
	[T4_KILLS] [float] NOT NULL,
	[StartingT4_KILLS] [float] NULL,
	[OverallT4_KILLSDelta] [float] NULL,
	[T4_KILLSDelta12Months] [float] NOT NULL,
	[T4_KILLSDelta6Months] [float] NOT NULL,
	[T4_KILLSDelta3Months] [float] NOT NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KILL4SUMMARY]') AND name = N'UX_KILL4SUMMARY_GovernorID')
CREATE UNIQUE NONCLUSTERED INDEX [UX_KILL4SUMMARY_GovernorID] ON [dbo].[KILL4SUMMARY]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
