SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALL_GOVS_ALLIANCES_SYNC_STATE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ALL_GOVS_ALLIANCES_SYNC_STATE](
	[StateID] [tinyint] NOT NULL,
	[LastProcessedScanOrder] [float] NOT NULL,
	[LastProcessedScanDate] [datetime] NULL,
	[LastRunAt] [datetime] NULL,
 CONSTRAINT [PK_ALL_GOVS_ALLIANCES_SYNC_STATE] PRIMARY KEY CLUSTERED 
(
	[StateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_ALL_GOVS_ALLIANCES_SYNC_STATE_LastProcessedScanOrder]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ALL_GOVS_ALLIANCES_SYNC_STATE] ADD  CONSTRAINT [DF_ALL_GOVS_ALLIANCES_SYNC_STATE_LastProcessedScanOrder]  DEFAULT ((0)) FOR [LastProcessedScanOrder]
END

