SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LATEST_GOVERNORNAME]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LATEST_GOVERNORNAME](
	[GovernorID] [float] NOT NULL,
	[TRIM_NAME] [nvarchar](255) COLLATE Latin1_General_CI_AS NULL,
	[GovernorName] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[SCANORDER] [float] NOT NULL
) ON [PRIMARY]
END
