SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T5KillDelta]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[T5KillDelta](
	[GovernorID] [float] NOT NULL,
	[DeltaOrder] [float] NOT NULL,
	[T5KILLSDelta] [float] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[T5KillDelta]') AND name = N'IX_T5KillDelta_DeltaOrder')
CREATE NONCLUSTERED INDEX [IX_T5KillDelta_DeltaOrder] ON [dbo].[T5KillDelta]
(
	[DeltaOrder] ASC
)
INCLUDE([GovernorID],[T5KILLSDelta]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
