SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KILLPOINTS_ALL]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[KILLPOINTS_ALL](
	[GovernorID] [float] NOT NULL,
	[GovernorName] [nvarchar](255) COLLATE Latin1_General_CI_AS NULL,
	[KillPoints] [bigint] NULL,
	[ScanDate] [datetime] NULL,
	[RowAscALL] [int] NULL,
	[RowDescALL] [int] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[KILLPOINTS_ALL]') AND name = N'IX_KILLPOINTS_ALL_GovernorID')
CREATE NONCLUSTERED INDEX [IX_KILLPOINTS_ALL_GovernorID] ON [dbo].[KILLPOINTS_ALL]
(
	[GovernorID] ASC
)
INCLUDE([KillPoints],[RowAscALL],[RowDescALL]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
