SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KVKTargetBands]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[KVKTargetBands](
	[KVKVersion] [int] NOT NULL,
	[MinPower] [bigint] NOT NULL,
	[KillTarget] [int] NULL,
	[MinKillTarget] [int] NULL,
	[DeadTarget] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[KVKVersion] ASC,
	[MinPower] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
