SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CURRENT_TARGETS_NEW_SEPT24]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CURRENT_TARGETS_NEW_SEPT24](
	[GovernorID] [float] NOT NULL,
	[KILL_TARGET] [int] NULL,
	[DEAD_TARGET] [int] NULL
) ON [PRIMARY]
END
