SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RANGEDSUMMARY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RANGEDSUMMARY](
	[GovernorID] [bigint] NOT NULL,
	[GovernorName] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PowerRank] [int] NULL,
	[RangedPoints] [bigint] NULL,
	[StartingRanged] [bigint] NULL,
	[OverallRangedDelta] [bigint] NULL,
	[RangedDelta12Months] [bigint] NULL,
	[RangedDelta6Months] [bigint] NULL,
	[RangedDelta3Months] [bigint] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RANGEDSUMMARY]') AND name = N'IX_RANGEDSUMMARY_PowerRank')
CREATE NONCLUSTERED INDEX [IX_RANGEDSUMMARY_PowerRank] ON [dbo].[RANGEDSUMMARY]
(
	[PowerRank] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RANGEDSUMMARY]') AND name = N'PK_RANGEDSUMMARY_Gov')
CREATE UNIQUE NONCLUSTERED INDEX [PK_RANGEDSUMMARY_Gov] ON [dbo].[RANGEDSUMMARY]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RANGEDSUMMARY]') AND name = N'UX_RANGEDSUMMARY_GovernorID')
CREATE UNIQUE NONCLUSTERED INDEX [UX_RANGEDSUMMARY_GovernorID] ON [dbo].[RANGEDSUMMARY]
(
	[GovernorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
