SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TARGETS_JUN25]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TARGETS_JUN25](
	[GovernorID] [float] NOT NULL,
	[KILL_TARGET] [int] NULL,
	[MINIMUM_KILL_TARGET] [int] NULL,
	[DEAD_TARGET] [int] NULL
) ON [PRIMARY]
END
