SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RANGED_D12]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RANGED_D12](
	[GovernorID] [bigint] NOT NULL,
	[RangedPoints] [bigint] NULL,
	[ScanDate] [datetime] NULL,
	[RowAsc12] [int] NULL,
	[RowDesc12] [int] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RANGED_D12]') AND name = N'IX_RANGED_D12_Gov_Scan')
CREATE NONCLUSTERED INDEX [IX_RANGED_D12_Gov_Scan] ON [dbo].[RANGED_D12]
(
	[GovernorID] ASC,
	[ScanDate] DESC
)
INCLUDE([RangedPoints]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
