SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[v_TARGETS_FOR_UPLOAD]'))
EXECUTE dbo.sp_executesql N'
CREATE VIEW [dbo].[v_TARGETS_FOR_UPLOAD]  AS 
SELECT * FROM [dbo].[EXCEL_EXPORT_KVK_TARGETS_13];

'
