SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PlayerKVKHistory]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PlayerKVKHistory](
	[GovernorID] [bigint] NOT NULL,
	[KVK_NUMBER] [int] NOT NULL,
	[KVK_KILL_RANK] [int] NULL,
	[KillPercent] [decimal](6, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[GovernorID] ASC,
	[KVK_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PlayerKVKHistory]') AND name = N'IX_PlayerKVKHistory_Last3')
CREATE NONCLUSTERED INDEX [IX_PlayerKVKHistory_Last3] ON [dbo].[PlayerKVKHistory]
(
	[GovernorID] ASC,
	[KVK_NUMBER] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
