SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RALLY_EXPORT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RALLY_EXPORT](
	[GOVENOR] [nvarchar](4000) COLLATE Latin1_General_CI_AS NOT NULL,
	[RALLY_LAUNCHED] [int] NOT NULL,
	[RALLY_JOINED] [int] NULL,
	[TOTAL_RALLIES_COMPLETED] [int] NULL
) ON [PRIMARY]
END
