SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

-- S2B reference snapshot; deploy the reviewed migration, not this file.
CREATE TABLE KVK.SourcePlayerResult
(
    PublicationID uniqueidentifier NOT NULL,
    SourceKey varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    KVK_NO int NOT NULL,
    ConfigVersionID uniqueidentifier NOT NULL,
    RosterID uniqueidentifier NOT NULL,
    GovernorID bigint NOT NULL,
    b0_kingdom int NOT NULL,
    CampID tinyint NOT NULL,
    name nvarchar(256) NULL,
    FieldStatusJson nvarchar(4000) COLLATE Latin1_General_100_BIN2 NOT NULL,
    starting_power bigint NULL,
    starting_power_rank int NULL,
    starting_power_cohort int NULL,
    power bigint NULL,
    power_rank int NULL,
    power_cohort int NULL,
    troops_power bigint NULL,
    troops_power_rank int NULL,
    troops_power_cohort int NULL,
    t1_kills bigint NULL,
    t1_kills_rank int NULL,
    t1_kills_cohort int NULL,
    t2_kills bigint NULL,
    t2_kills_rank int NULL,
    t2_kills_cohort int NULL,
    t3_kills bigint NULL,
    t3_kills_rank int NULL,
    t3_kills_cohort int NULL,
    t4_kills bigint NULL,
    t4_kills_rank int NULL,
    t4_kills_cohort int NULL,
    t5_kills bigint NULL,
    t5_kills_rank int NULL,
    t5_kills_cohort int NULL,
    total_kill_points bigint NULL,
    total_kill_points_rank int NULL,
    total_kill_points_cohort int NULL,
    dead bigint NULL,
    dead_rank int NULL,
    dead_cohort int NULL,
    healed bigint NULL,
    healed_rank int NULL,
    healed_cohort int NULL,
    acclaim bigint NULL,
    acclaim_rank int NULL,
    acclaim_cohort int NULL,
    highest_acclaim bigint NULL,
    highest_acclaim_rank int NULL,
    highest_acclaim_cohort int NULL,
    kp_t4_t5 decimal(38,6) NULL,
    kp_t4_t5_rank int NULL,
    kp_t4_t5_cohort int NULL,
    dkp decimal(38,6) NULL,
    dkp_rank int NULL,
    dkp_cohort int NULL,
    healed_points decimal(38,6) NULL,
    healed_points_rank int NULL,
    healed_points_cohort int NULL,
    dkp_power_ratio decimal(38,12) NULL,
    dkp_power_ratio_rank int NULL,
    dkp_power_ratio_cohort int NULL,
    CONSTRAINT PK_SourcePlayerResult PRIMARY KEY (PublicationID, GovernorID),
    CONSTRAINT FK_SourcePlayerResult_Publication FOREIGN KEY (SourceKey, KVK_NO, PublicationID, ConfigVersionID, RosterID) REFERENCES KVK.SourcePublication (SourceKey, KVK_NO, PublicationID, ConfigVersionID, RosterID),
    CONSTRAINT FK_SourcePlayerResult_Eligible FOREIGN KEY (RosterID, GovernorID, b0_kingdom) REFERENCES KVK.SourceRosterMember (RosterID, GovernorID, b0_kingdom),
    CONSTRAINT FK_SourcePlayerResult_Camp FOREIGN KEY (ConfigVersionID, b0_kingdom, CampID) REFERENCES KVK.SourceCampConfig (ConfigVersionID, Kingdom, CampID),
    CONSTRAINT CK_SourcePlayerResult_StatusJson CHECK (ISJSON(FieldStatusJson) = 1),
    CONSTRAINT CK_SourcePlayerResult_Identity CHECK (GovernorID > 0 AND b0_kingdom > 0 AND CampID BETWEEN 1 AND 8),
    CONSTRAINT CK_SourcePlayerResult_starting_power CHECK (JSON_VALUE(FieldStatusJson, '$.starting_power') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.starting_power')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.starting_power')) AND ((JSON_VALUE(FieldStatusJson, '$.starting_power') = N'available' AND starting_power IS NOT NULL AND starting_power >= 0) OR (JSON_VALUE(FieldStatusJson, '$.starting_power') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND starting_power IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_starting_power_Rank CHECK ((starting_power_rank IS NULL AND starting_power_cohort IS NULL) OR (starting_power IS NOT NULL AND starting_power_rank IS NOT NULL AND starting_power_cohort IS NOT NULL AND starting_power_rank >= 1 AND starting_power_rank <= starting_power_cohort AND starting_power_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_power CHECK (JSON_VALUE(FieldStatusJson, '$.power') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.power')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.power')) AND ((JSON_VALUE(FieldStatusJson, '$.power') = N'available' AND power IS NOT NULL) OR (JSON_VALUE(FieldStatusJson, '$.power') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND power IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_power_Rank CHECK ((power_rank IS NULL AND power_cohort IS NULL) OR (power IS NOT NULL AND power_rank IS NOT NULL AND power_cohort IS NOT NULL AND power_rank >= 1 AND power_rank <= power_cohort AND power_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_troops_power CHECK (JSON_VALUE(FieldStatusJson, '$.troops_power') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.troops_power')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.troops_power')) AND ((JSON_VALUE(FieldStatusJson, '$.troops_power') = N'available' AND troops_power IS NOT NULL) OR (JSON_VALUE(FieldStatusJson, '$.troops_power') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND troops_power IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_troops_power_Rank CHECK ((troops_power_rank IS NULL AND troops_power_cohort IS NULL) OR (troops_power IS NOT NULL AND troops_power_rank IS NOT NULL AND troops_power_cohort IS NOT NULL AND troops_power_rank >= 1 AND troops_power_rank <= troops_power_cohort AND troops_power_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_t1_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t1_kills') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.t1_kills')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.t1_kills')) AND ((JSON_VALUE(FieldStatusJson, '$.t1_kills') = N'available' AND t1_kills IS NOT NULL AND t1_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t1_kills') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND t1_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_t1_kills_Rank CHECK ((t1_kills_rank IS NULL AND t1_kills_cohort IS NULL) OR (t1_kills IS NOT NULL AND t1_kills_rank IS NOT NULL AND t1_kills_cohort IS NOT NULL AND t1_kills_rank >= 1 AND t1_kills_rank <= t1_kills_cohort AND t1_kills_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_t2_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t2_kills') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.t2_kills')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.t2_kills')) AND ((JSON_VALUE(FieldStatusJson, '$.t2_kills') = N'available' AND t2_kills IS NOT NULL AND t2_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t2_kills') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND t2_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_t2_kills_Rank CHECK ((t2_kills_rank IS NULL AND t2_kills_cohort IS NULL) OR (t2_kills IS NOT NULL AND t2_kills_rank IS NOT NULL AND t2_kills_cohort IS NOT NULL AND t2_kills_rank >= 1 AND t2_kills_rank <= t2_kills_cohort AND t2_kills_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_t3_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t3_kills') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.t3_kills')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.t3_kills')) AND ((JSON_VALUE(FieldStatusJson, '$.t3_kills') = N'available' AND t3_kills IS NOT NULL AND t3_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t3_kills') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND t3_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_t3_kills_Rank CHECK ((t3_kills_rank IS NULL AND t3_kills_cohort IS NULL) OR (t3_kills IS NOT NULL AND t3_kills_rank IS NOT NULL AND t3_kills_cohort IS NOT NULL AND t3_kills_rank >= 1 AND t3_kills_rank <= t3_kills_cohort AND t3_kills_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_t4_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t4_kills') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.t4_kills')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.t4_kills')) AND ((JSON_VALUE(FieldStatusJson, '$.t4_kills') = N'available' AND t4_kills IS NOT NULL AND t4_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t4_kills') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND t4_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_t4_kills_Rank CHECK ((t4_kills_rank IS NULL AND t4_kills_cohort IS NULL) OR (t4_kills IS NOT NULL AND t4_kills_rank IS NOT NULL AND t4_kills_cohort IS NOT NULL AND t4_kills_rank >= 1 AND t4_kills_rank <= t4_kills_cohort AND t4_kills_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_t5_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t5_kills') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.t5_kills')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.t5_kills')) AND ((JSON_VALUE(FieldStatusJson, '$.t5_kills') = N'available' AND t5_kills IS NOT NULL AND t5_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t5_kills') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND t5_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_t5_kills_Rank CHECK ((t5_kills_rank IS NULL AND t5_kills_cohort IS NULL) OR (t5_kills IS NOT NULL AND t5_kills_rank IS NOT NULL AND t5_kills_cohort IS NOT NULL AND t5_kills_rank >= 1 AND t5_kills_rank <= t5_kills_cohort AND t5_kills_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_total_kill_points CHECK (JSON_VALUE(FieldStatusJson, '$.total_kill_points') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.total_kill_points')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.total_kill_points')) AND ((JSON_VALUE(FieldStatusJson, '$.total_kill_points') = N'available' AND total_kill_points IS NOT NULL AND total_kill_points >= 0) OR (JSON_VALUE(FieldStatusJson, '$.total_kill_points') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND total_kill_points IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_total_kill_points_Rank CHECK ((total_kill_points_rank IS NULL AND total_kill_points_cohort IS NULL) OR (total_kill_points IS NOT NULL AND total_kill_points_rank IS NOT NULL AND total_kill_points_cohort IS NOT NULL AND total_kill_points_rank >= 1 AND total_kill_points_rank <= total_kill_points_cohort AND total_kill_points_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_dead CHECK (JSON_VALUE(FieldStatusJson, '$.dead') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.dead')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.dead')) AND ((JSON_VALUE(FieldStatusJson, '$.dead') = N'available' AND dead IS NOT NULL AND dead >= 0) OR (JSON_VALUE(FieldStatusJson, '$.dead') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND dead IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_dead_Rank CHECK ((dead_rank IS NULL AND dead_cohort IS NULL) OR (dead IS NOT NULL AND dead_rank IS NOT NULL AND dead_cohort IS NOT NULL AND dead_rank >= 1 AND dead_rank <= dead_cohort AND dead_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_healed CHECK (JSON_VALUE(FieldStatusJson, '$.healed') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.healed')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.healed')) AND ((JSON_VALUE(FieldStatusJson, '$.healed') = N'available' AND healed IS NOT NULL AND healed >= 0) OR (JSON_VALUE(FieldStatusJson, '$.healed') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND healed IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_healed_Rank CHECK ((healed_rank IS NULL AND healed_cohort IS NULL) OR (healed IS NOT NULL AND healed_rank IS NOT NULL AND healed_cohort IS NOT NULL AND healed_rank >= 1 AND healed_rank <= healed_cohort AND healed_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_acclaim CHECK (JSON_VALUE(FieldStatusJson, '$.acclaim') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.acclaim')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.acclaim')) AND ((JSON_VALUE(FieldStatusJson, '$.acclaim') = N'available' AND acclaim IS NOT NULL AND acclaim >= 0) OR (JSON_VALUE(FieldStatusJson, '$.acclaim') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND acclaim IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_acclaim_Rank CHECK ((acclaim_rank IS NULL AND acclaim_cohort IS NULL) OR (acclaim IS NOT NULL AND acclaim_rank IS NOT NULL AND acclaim_cohort IS NOT NULL AND acclaim_rank >= 1 AND acclaim_rank <= acclaim_cohort AND acclaim_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_highest_acclaim CHECK (JSON_VALUE(FieldStatusJson, '$.highest_acclaim') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.highest_acclaim')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.highest_acclaim')) AND ((JSON_VALUE(FieldStatusJson, '$.highest_acclaim') = N'available' AND highest_acclaim IS NOT NULL AND highest_acclaim >= 0) OR (JSON_VALUE(FieldStatusJson, '$.highest_acclaim') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND highest_acclaim IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_highest_acclaim_Rank CHECK ((highest_acclaim_rank IS NULL AND highest_acclaim_cohort IS NULL) OR (highest_acclaim IS NOT NULL AND highest_acclaim_rank IS NOT NULL AND highest_acclaim_cohort IS NOT NULL AND highest_acclaim_rank >= 1 AND highest_acclaim_rank <= highest_acclaim_cohort AND highest_acclaim_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_kp_t4_t5 CHECK (JSON_VALUE(FieldStatusJson, '$.kp_t4_t5') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.kp_t4_t5')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.kp_t4_t5')) AND ((JSON_VALUE(FieldStatusJson, '$.kp_t4_t5') = N'available' AND kp_t4_t5 IS NOT NULL AND kp_t4_t5 >= 0) OR (JSON_VALUE(FieldStatusJson, '$.kp_t4_t5') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND kp_t4_t5 IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_kp_t4_t5_Rank CHECK ((kp_t4_t5_rank IS NULL AND kp_t4_t5_cohort IS NULL) OR (kp_t4_t5 IS NOT NULL AND kp_t4_t5_rank IS NOT NULL AND kp_t4_t5_cohort IS NOT NULL AND kp_t4_t5_rank >= 1 AND kp_t4_t5_rank <= kp_t4_t5_cohort AND kp_t4_t5_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_dkp CHECK (JSON_VALUE(FieldStatusJson, '$.dkp') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.dkp')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.dkp')) AND ((JSON_VALUE(FieldStatusJson, '$.dkp') = N'available' AND dkp IS NOT NULL) OR (JSON_VALUE(FieldStatusJson, '$.dkp') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND dkp IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_dkp_Rank CHECK ((dkp_rank IS NULL AND dkp_cohort IS NULL) OR (dkp IS NOT NULL AND dkp_rank IS NOT NULL AND dkp_cohort IS NOT NULL AND dkp_rank >= 1 AND dkp_rank <= dkp_cohort AND dkp_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_healed_points CHECK (JSON_VALUE(FieldStatusJson, '$.healed_points') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.healed_points')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.healed_points')) AND ((JSON_VALUE(FieldStatusJson, '$.healed_points') = N'available' AND healed_points IS NOT NULL AND healed_points >= 0) OR (JSON_VALUE(FieldStatusJson, '$.healed_points') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND healed_points IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_healed_points_Rank CHECK ((healed_points_rank IS NULL AND healed_points_cohort IS NULL) OR (healed_points IS NOT NULL AND healed_points_rank IS NOT NULL AND healed_points_cohort IS NOT NULL AND healed_points_rank >= 1 AND healed_points_rank <= healed_points_cohort AND healed_points_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_dkp_power_ratio CHECK (JSON_VALUE(FieldStatusJson, '$.dkp_power_ratio') IS NOT NULL AND DATALENGTH(JSON_VALUE(FieldStatusJson, '$.dkp_power_ratio')) = 2 * LEN(JSON_VALUE(FieldStatusJson, '$.dkp_power_ratio')) AND ((JSON_VALUE(FieldStatusJson, '$.dkp_power_ratio') = N'available' AND dkp_power_ratio IS NOT NULL) OR (JSON_VALUE(FieldStatusJson, '$.dkp_power_ratio') IN (N'missing_start',N'missing_end',N'invalid_source_value',N'counter_regression',N'unsupported',N'missing_configuration',N'not_applicable') AND dkp_power_ratio IS NULL))),
    CONSTRAINT CK_SourcePlayerResult_dkp_power_ratio_Rank CHECK ((dkp_power_ratio_rank IS NULL AND dkp_power_ratio_cohort IS NULL) OR (dkp_power_ratio IS NOT NULL AND dkp_power_ratio_rank IS NOT NULL AND dkp_power_ratio_cohort IS NOT NULL AND dkp_power_ratio_rank >= 1 AND dkp_power_ratio_rank <= dkp_power_ratio_cohort AND dkp_power_ratio_cohort <= 50000)),
    CONSTRAINT CK_SourcePlayerResult_Scope CHECK (SourceKey = 'snapshot_report_v1' AND DATALENGTH(SourceKey) = 18 AND KVK_NO > 0)
);
CREATE INDEX IX_SourcePlayerResult_Kingdom ON KVK.SourcePlayerResult (PublicationID, b0_kingdom);
CREATE INDEX IX_SourcePlayerResult_Camp ON KVK.SourcePlayerResult (PublicationID, CampID);
