SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

-- S2A reference snapshot; deploy the reviewed migration, not this file.
CREATE TABLE KVK.SourceKingdomReportRow
(
    RevisionID uniqueidentifier NOT NULL,
    SourceKey varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    KVK_NO int NOT NULL,
    Kingdom int NOT NULL,
    CampID tinyint NOT NULL,
    CampLabel nvarchar(256) NOT NULL,
    MappingDigest binary(32) NOT NULL,
    t4_kills decimal(38,6) NOT NULL,
    t4_kills_raw nvarchar(128) NOT NULL,
    t4_kills_unit decimal(38,6) NOT NULL,
    t4_kills_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    t5_kills decimal(38,6) NOT NULL,
    t5_kills_raw nvarchar(128) NOT NULL,
    t5_kills_unit decimal(38,6) NOT NULL,
    t5_kills_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    kp_t4_t5 decimal(38,6) NOT NULL,
    kp_t4_t5_raw nvarchar(128) NOT NULL,
    kp_t4_t5_unit decimal(38,6) NOT NULL,
    kp_t4_t5_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    dead decimal(38,6) NOT NULL,
    dead_raw nvarchar(128) NOT NULL,
    dead_unit decimal(38,6) NOT NULL,
    dead_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    t4_t5_dead decimal(38,6) NOT NULL,
    t4_t5_dead_raw nvarchar(128) NOT NULL,
    t4_t5_dead_unit decimal(38,6) NOT NULL,
    t4_t5_dead_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    healed decimal(38,6) NOT NULL,
    healed_raw nvarchar(128) NOT NULL,
    healed_unit decimal(38,6) NOT NULL,
    healed_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    acclaim decimal(38,6) NOT NULL,
    acclaim_raw nvarchar(128) NOT NULL,
    acclaim_unit decimal(38,6) NOT NULL,
    acclaim_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    dkp decimal(38,6) NOT NULL,
    dkp_raw nvarchar(128) NOT NULL,
    dkp_unit decimal(38,6) NOT NULL,
    dkp_precision varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RawCellsJson nvarchar(max) NOT NULL,
    CONSTRAINT PK_SourceKingdomReportRow PRIMARY KEY (RevisionID, Kingdom),
    CONSTRAINT FK_SourceKingdomReportRow_Revision FOREIGN KEY (SourceKey, KVK_NO, RevisionID, MappingDigest) REFERENCES KVK.SourceAggregateRevision (SourceKey, KVK_NO, RevisionID, MappingDigest),
    CONSTRAINT CK_SourceKingdomReportRow_Scope CHECK (SourceKey = 'snapshot_report_v1' AND DATALENGTH(SourceKey) = 18 AND KVK_NO > 0),
    CONSTRAINT CK_SourceKingdomReportRow_Identity CHECK (Kingdom > 0 AND CampID BETWEEN 1 AND 8 AND LEN(CampLabel) > 0),
    CONSTRAINT CK_SourceKingdomReportRow_Raw CHECK (ISJSON(RawCellsJson) = 1 AND DATALENGTH(RawCellsJson) <= 1048576),
    CONSTRAINT CK_SourceKingdomReportRow_t4_kills CHECK (t4_kills >= 0 AND t4_kills_unit > 0 AND LEN(t4_kills_raw) > 0 AND t4_kills_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_t5_kills CHECK (t5_kills >= 0 AND t5_kills_unit > 0 AND LEN(t5_kills_raw) > 0 AND t5_kills_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_kp_t4_t5 CHECK (kp_t4_t5 >= 0 AND kp_t4_t5_unit > 0 AND LEN(kp_t4_t5_raw) > 0 AND kp_t4_t5_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_dead CHECK (dead >= 0 AND dead_unit > 0 AND LEN(dead_raw) > 0 AND dead_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_t4_t5_dead CHECK (t4_t5_dead >= 0 AND t4_t5_dead_unit > 0 AND LEN(t4_t5_dead_raw) > 0 AND t4_t5_dead_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_healed CHECK (healed >= 0 AND healed_unit > 0 AND LEN(healed_raw) > 0 AND healed_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_acclaim CHECK (acclaim >= 0 AND acclaim_unit > 0 AND LEN(acclaim_raw) > 0 AND acclaim_precision IN ('reported_numeric','reported_abbreviated')),
    CONSTRAINT CK_SourceKingdomReportRow_dkp CHECK (dkp >= 0 AND dkp_unit > 0 AND LEN(dkp_raw) > 0 AND dkp_precision IN ('reported_numeric','reported_abbreviated'))
);
