SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[KVK].[KVK_Scan]') AND type in (N'U'))
BEGIN
CREATE TABLE [KVK].[KVK_Scan](
	[KVK_NO] [int] NOT NULL,
	[ScanID] [int] NOT NULL,
	[ScanTimestampUTC] [datetime2](0) NOT NULL,
	[SourceFileName] [nvarchar](255) COLLATE Latin1_General_CI_AS NOT NULL,
	[FileHash] [varbinary](32) NOT NULL,
	[Row_Count] [int] NOT NULL,
	[ImportedAtUTC] [datetime2](0) NOT NULL,
	[UploaderDiscordID] [bigint] NULL,
 CONSTRAINT [PK_KVK_Scan] PRIMARY KEY CLUSTERED 
(
	[KVK_NO] ASC,
	[ScanID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_KVK_Scan_File] UNIQUE NONCLUSTERED 
(
	[KVK_NO] ASC,
	[ScanTimestampUTC] ASC,
	[FileHash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[KVK].[KVK_Scan]') AND name = N'IX_KVK_Scan_ScanTimestamp')
CREATE NONCLUSTERED INDEX [IX_KVK_Scan_ScanTimestamp] ON [KVK].[KVK_Scan]
(
	[ScanTimestampUTC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[KVK].[DF_KVK_Scan_ImportedAtUTC]') AND type = 'D')
BEGIN
ALTER TABLE [KVK].[KVK_Scan] ADD  CONSTRAINT [DF_KVK_Scan_ImportedAtUTC]  DEFAULT (sysutcdatetime()) FOR [ImportedAtUTC]
END

