SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

-- S2A reference snapshot; deploy the reviewed migration, not this file.
CREATE TABLE KVK.SourcePlayerSnapshot
(
    RevisionID uniqueidentifier NOT NULL,
    SourceKey varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    KVK_NO int NOT NULL,
    GovernorID bigint NOT NULL,
    kingdom int NOT NULL,
    name nvarchar(256) NULL,
    alliance nvarchar(256) NULL,
    civilization nvarchar(256) NULL,
    power bigint NULL,
    city_hall bigint NULL,
    vip bigint NULL,
    t1_kills bigint NULL,
    t2_kills bigint NULL,
    t3_kills bigint NULL,
    t4_kills bigint NULL,
    t5_kills bigint NULL,
    total_kill_points bigint NULL,
    ranged_points bigint NULL,
    dead bigint NULL,
    healed bigint NULL,
    rss_assistance bigint NULL,
    alliance_helps bigint NULL,
    rss_gathered bigint NULL,
    troops_power bigint NULL,
    tech_power bigint NULL,
    building_power bigint NULL,
    commander_power bigint NULL,
    kvk_played bigint NULL,
    autarch_times bigint NULL,
    most_kvk_kill bigint NULL,
    most_kvk_dead bigint NULL,
    most_kvk_heal bigint NULL,
    acclaim bigint NULL,
    highest_acclaim bigint NULL,
    aoo_joined bigint NULL,
    aoo_won bigint NULL,
    aoo_avg_kill bigint NULL,
    aoo_avg_dead bigint NULL,
    aoo_avg_heal bigint NULL,
    FieldStatusJson nvarchar(4000) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RawProfileJson nvarchar(max) NOT NULL,
    CONSTRAINT PK_SourcePlayerSnapshot PRIMARY KEY (RevisionID, GovernorID),
    CONSTRAINT FK_SourcePlayerSnapshot_Revision FOREIGN KEY (SourceKey, KVK_NO, RevisionID) REFERENCES KVK.SourceObservationRevision (SourceKey, KVK_NO, RevisionID),
    CONSTRAINT CK_SourcePlayerSnapshot_Scope CHECK (SourceKey = 'snapshot_report_v1' AND DATALENGTH(SourceKey) = 18 AND KVK_NO > 0),
    CONSTRAINT CK_SourcePlayerSnapshot_Identity CHECK (GovernorID > 0 AND kingdom > 0),
    CONSTRAINT CK_SourcePlayerSnapshot_Json CHECK (ISJSON(FieldStatusJson) = 1 AND ISJSON(RawProfileJson) = 1 AND DATALENGTH(RawProfileJson) <= 16777216),
    CONSTRAINT CK_SourcePlayerSnapshot_power CHECK (JSON_VALUE(FieldStatusJson, '$.power') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.power') = 'available' AND power IS NOT NULL AND power >= 0) OR (JSON_VALUE(FieldStatusJson, '$.power') IN ('invalid_source_value','unsupported','not_applicable') AND power IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_city_hall CHECK (JSON_VALUE(FieldStatusJson, '$.city_hall') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.city_hall') = 'available' AND city_hall IS NOT NULL AND city_hall >= 0) OR (JSON_VALUE(FieldStatusJson, '$.city_hall') IN ('invalid_source_value','unsupported','not_applicable') AND city_hall IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_vip CHECK (JSON_VALUE(FieldStatusJson, '$.vip') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.vip') = 'available' AND vip IS NOT NULL AND vip >= 0) OR (JSON_VALUE(FieldStatusJson, '$.vip') IN ('invalid_source_value','unsupported','not_applicable') AND vip IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_t1_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t1_kills') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.t1_kills') = 'available' AND t1_kills IS NOT NULL AND t1_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t1_kills') IN ('invalid_source_value','unsupported','not_applicable') AND t1_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_t2_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t2_kills') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.t2_kills') = 'available' AND t2_kills IS NOT NULL AND t2_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t2_kills') IN ('invalid_source_value','unsupported','not_applicable') AND t2_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_t3_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t3_kills') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.t3_kills') = 'available' AND t3_kills IS NOT NULL AND t3_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t3_kills') IN ('invalid_source_value','unsupported','not_applicable') AND t3_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_t4_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t4_kills') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.t4_kills') = 'available' AND t4_kills IS NOT NULL AND t4_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t4_kills') IN ('invalid_source_value','unsupported','not_applicable') AND t4_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_t5_kills CHECK (JSON_VALUE(FieldStatusJson, '$.t5_kills') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.t5_kills') = 'available' AND t5_kills IS NOT NULL AND t5_kills >= 0) OR (JSON_VALUE(FieldStatusJson, '$.t5_kills') IN ('invalid_source_value','unsupported','not_applicable') AND t5_kills IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_total_kill_points CHECK (JSON_VALUE(FieldStatusJson, '$.total_kill_points') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.total_kill_points') = 'available' AND total_kill_points IS NOT NULL AND total_kill_points >= 0) OR (JSON_VALUE(FieldStatusJson, '$.total_kill_points') IN ('invalid_source_value','unsupported','not_applicable') AND total_kill_points IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_ranged_points CHECK (JSON_VALUE(FieldStatusJson, '$.ranged_points') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.ranged_points') = 'available' AND ranged_points IS NOT NULL AND ranged_points >= 0) OR (JSON_VALUE(FieldStatusJson, '$.ranged_points') IN ('invalid_source_value','unsupported','not_applicable') AND ranged_points IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_dead CHECK (JSON_VALUE(FieldStatusJson, '$.dead') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.dead') = 'available' AND dead IS NOT NULL AND dead >= 0) OR (JSON_VALUE(FieldStatusJson, '$.dead') IN ('invalid_source_value','unsupported','not_applicable') AND dead IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_healed CHECK (JSON_VALUE(FieldStatusJson, '$.healed') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.healed') = 'available' AND healed IS NOT NULL AND healed >= 0) OR (JSON_VALUE(FieldStatusJson, '$.healed') IN ('invalid_source_value','unsupported','not_applicable') AND healed IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_rss_assistance CHECK (JSON_VALUE(FieldStatusJson, '$.rss_assistance') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.rss_assistance') = 'available' AND rss_assistance IS NOT NULL AND rss_assistance >= 0) OR (JSON_VALUE(FieldStatusJson, '$.rss_assistance') IN ('invalid_source_value','unsupported','not_applicable') AND rss_assistance IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_alliance_helps CHECK (JSON_VALUE(FieldStatusJson, '$.alliance_helps') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.alliance_helps') = 'available' AND alliance_helps IS NOT NULL AND alliance_helps >= 0) OR (JSON_VALUE(FieldStatusJson, '$.alliance_helps') IN ('invalid_source_value','unsupported','not_applicable') AND alliance_helps IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_rss_gathered CHECK (JSON_VALUE(FieldStatusJson, '$.rss_gathered') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.rss_gathered') = 'available' AND rss_gathered IS NOT NULL AND rss_gathered >= 0) OR (JSON_VALUE(FieldStatusJson, '$.rss_gathered') IN ('invalid_source_value','unsupported','not_applicable') AND rss_gathered IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_troops_power CHECK (JSON_VALUE(FieldStatusJson, '$.troops_power') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.troops_power') = 'available' AND troops_power IS NOT NULL AND troops_power >= 0) OR (JSON_VALUE(FieldStatusJson, '$.troops_power') IN ('invalid_source_value','unsupported','not_applicable') AND troops_power IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_tech_power CHECK (JSON_VALUE(FieldStatusJson, '$.tech_power') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.tech_power') = 'available' AND tech_power IS NOT NULL AND tech_power >= 0) OR (JSON_VALUE(FieldStatusJson, '$.tech_power') IN ('invalid_source_value','unsupported','not_applicable') AND tech_power IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_building_power CHECK (JSON_VALUE(FieldStatusJson, '$.building_power') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.building_power') = 'available' AND building_power IS NOT NULL AND building_power >= 0) OR (JSON_VALUE(FieldStatusJson, '$.building_power') IN ('invalid_source_value','unsupported','not_applicable') AND building_power IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_commander_power CHECK (JSON_VALUE(FieldStatusJson, '$.commander_power') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.commander_power') = 'available' AND commander_power IS NOT NULL AND commander_power >= 0) OR (JSON_VALUE(FieldStatusJson, '$.commander_power') IN ('invalid_source_value','unsupported','not_applicable') AND commander_power IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_kvk_played CHECK (JSON_VALUE(FieldStatusJson, '$.kvk_played') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.kvk_played') = 'available' AND kvk_played IS NOT NULL AND kvk_played >= 0) OR (JSON_VALUE(FieldStatusJson, '$.kvk_played') IN ('invalid_source_value','unsupported','not_applicable') AND kvk_played IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_autarch_times CHECK (JSON_VALUE(FieldStatusJson, '$.autarch_times') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.autarch_times') = 'available' AND autarch_times IS NOT NULL AND autarch_times >= 0) OR (JSON_VALUE(FieldStatusJson, '$.autarch_times') IN ('invalid_source_value','unsupported','not_applicable') AND autarch_times IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_most_kvk_kill CHECK (JSON_VALUE(FieldStatusJson, '$.most_kvk_kill') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.most_kvk_kill') = 'available' AND most_kvk_kill IS NOT NULL AND most_kvk_kill >= 0) OR (JSON_VALUE(FieldStatusJson, '$.most_kvk_kill') IN ('invalid_source_value','unsupported','not_applicable') AND most_kvk_kill IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_most_kvk_dead CHECK (JSON_VALUE(FieldStatusJson, '$.most_kvk_dead') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.most_kvk_dead') = 'available' AND most_kvk_dead IS NOT NULL AND most_kvk_dead >= 0) OR (JSON_VALUE(FieldStatusJson, '$.most_kvk_dead') IN ('invalid_source_value','unsupported','not_applicable') AND most_kvk_dead IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_most_kvk_heal CHECK (JSON_VALUE(FieldStatusJson, '$.most_kvk_heal') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.most_kvk_heal') = 'available' AND most_kvk_heal IS NOT NULL AND most_kvk_heal >= 0) OR (JSON_VALUE(FieldStatusJson, '$.most_kvk_heal') IN ('invalid_source_value','unsupported','not_applicable') AND most_kvk_heal IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_acclaim CHECK (JSON_VALUE(FieldStatusJson, '$.acclaim') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.acclaim') = 'available' AND acclaim IS NOT NULL AND acclaim >= 0) OR (JSON_VALUE(FieldStatusJson, '$.acclaim') IN ('invalid_source_value','unsupported','not_applicable') AND acclaim IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_highest_acclaim CHECK (JSON_VALUE(FieldStatusJson, '$.highest_acclaim') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.highest_acclaim') = 'available' AND highest_acclaim IS NOT NULL AND highest_acclaim >= 0) OR (JSON_VALUE(FieldStatusJson, '$.highest_acclaim') IN ('invalid_source_value','unsupported','not_applicable') AND highest_acclaim IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_aoo_joined CHECK (JSON_VALUE(FieldStatusJson, '$.aoo_joined') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.aoo_joined') = 'available' AND aoo_joined IS NOT NULL AND aoo_joined >= 0) OR (JSON_VALUE(FieldStatusJson, '$.aoo_joined') IN ('invalid_source_value','unsupported','not_applicable') AND aoo_joined IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_aoo_won CHECK (JSON_VALUE(FieldStatusJson, '$.aoo_won') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.aoo_won') = 'available' AND aoo_won IS NOT NULL AND aoo_won >= 0) OR (JSON_VALUE(FieldStatusJson, '$.aoo_won') IN ('invalid_source_value','unsupported','not_applicable') AND aoo_won IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_aoo_avg_kill CHECK (JSON_VALUE(FieldStatusJson, '$.aoo_avg_kill') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.aoo_avg_kill') = 'available' AND aoo_avg_kill IS NOT NULL AND aoo_avg_kill >= 0) OR (JSON_VALUE(FieldStatusJson, '$.aoo_avg_kill') IN ('invalid_source_value','unsupported','not_applicable') AND aoo_avg_kill IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_aoo_avg_dead CHECK (JSON_VALUE(FieldStatusJson, '$.aoo_avg_dead') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.aoo_avg_dead') = 'available' AND aoo_avg_dead IS NOT NULL AND aoo_avg_dead >= 0) OR (JSON_VALUE(FieldStatusJson, '$.aoo_avg_dead') IN ('invalid_source_value','unsupported','not_applicable') AND aoo_avg_dead IS NULL))),
    CONSTRAINT CK_SourcePlayerSnapshot_aoo_avg_heal CHECK (JSON_VALUE(FieldStatusJson, '$.aoo_avg_heal') IS NOT NULL AND ((JSON_VALUE(FieldStatusJson, '$.aoo_avg_heal') = 'available' AND aoo_avg_heal IS NOT NULL AND aoo_avg_heal >= 0) OR (JSON_VALUE(FieldStatusJson, '$.aoo_avg_heal') IN ('invalid_source_value','unsupported','not_applicable') AND aoo_avg_heal IS NULL)))
);
