SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RALLY_STARTED]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RALLY_STARTED](
	[GovernorName] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[GovernorID] [float] NOT NULL,
	[RALLY_STARTED] [int] NULL
) ON [PRIMARY]
END
