SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[P3]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[P3](
	[GovernorID] [float] NOT NULL,
	[POWER] [float] NOT NULL,
	[ScanDate] [datetime] NOT NULL,
	[RowAsc3] [bigint] NULL,
	[RowDesc3] [bigint] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[P3]') AND name = N'IX_P3_GovernorID')
CREATE NONCLUSTERED INDEX [IX_P3_GovernorID] ON [dbo].[P3]
(
	[GovernorID] ASC
)
INCLUDE([POWER],[RowAsc3],[RowDesc3]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
