SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[KVK].[KVK_DKPWeights]') AND type in (N'U'))
BEGIN
CREATE TABLE [KVK].[KVK_DKPWeights](
	[KVK_NO] [int] NOT NULL,
	[WeightT4X] [float] NOT NULL,
	[WeightT5Y] [float] NOT NULL,
	[WeightDeadsZ] [float] NOT NULL,
	[EffectiveFromUTC] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_KVK_DKPWeights] PRIMARY KEY CLUSTERED 
(
	[KVK_NO] ASC,
	[EffectiveFromUTC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[KVK].[KVK_DKPWeights]') AND name = N'IX_KVK_DKPWeights_KVK')
CREATE NONCLUSTERED INDEX [IX_KVK_DKPWeights_KVK] ON [KVK].[KVK_DKPWeights]
(
	[KVK_NO] ASC
)
INCLUDE([WeightT4X],[WeightT5Y],[WeightDeadsZ],[EffectiveFromUTC]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[KVK].[KVK_DKPWeights]') AND name = N'IX_KVK_DKPWeights_KVK_NO_EffectiveFromUTC')
CREATE NONCLUSTERED INDEX [IX_KVK_DKPWeights_KVK_NO_EffectiveFromUTC] ON [KVK].[KVK_DKPWeights]
(
	[KVK_NO] ASC,
	[EffectiveFromUTC] DESC
)
INCLUDE([WeightT4X],[WeightT5Y],[WeightDeadsZ]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[KVK].[DF_Weights_Eff]') AND type = 'D')
BEGIN
ALTER TABLE [KVK].[KVK_DKPWeights] ADD  CONSTRAINT [DF_Weights_Eff]  DEFAULT (sysutcdatetime()) FOR [EffectiveFromUTC]
END

