SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[KVK].[KVK_CampMap]') AND type in (N'U'))
BEGIN
CREATE TABLE [KVK].[KVK_CampMap](
	[KVK_NO] [int] NOT NULL,
	[Kingdom] [int] NOT NULL,
	[CampID] [tinyint] NOT NULL,
	[CampName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_KVK_CampMap] PRIMARY KEY CLUSTERED 
(
	[KVK_NO] ASC,
	[Kingdom] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[KVK].[KVK_CampMap]') AND name = N'IX_KVK_CampMap_Camp')
CREATE NONCLUSTERED INDEX [IX_KVK_CampMap_Camp] ON [KVK].[KVK_CampMap]
(
	[KVK_NO] ASC,
	[CampID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[KVK].[KVK_CampMap]') AND name = N'IX_KVK_CampMap_KVK_NO_Kingdom')
CREATE NONCLUSTERED INDEX [IX_KVK_CampMap_KVK_NO_Kingdom] ON [KVK].[KVK_CampMap]
(
	[KVK_NO] ASC,
	[Kingdom] ASC
)
INCLUDE([CampID],[CampName]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[KVK].[CK_KVK_CampMap_CampID]') AND parent_object_id = OBJECT_ID(N'[KVK].[KVK_CampMap]'))
ALTER TABLE [KVK].[KVK_CampMap]  WITH CHECK ADD  CONSTRAINT [CK_KVK_CampMap_CampID] CHECK  (([CampID]>=(1) AND [CampID]<=(8)))
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[KVK].[CK_KVK_CampMap_CampID]') AND parent_object_id = OBJECT_ID(N'[KVK].[KVK_CampMap]'))
ALTER TABLE [KVK].[KVK_CampMap] CHECK CONSTRAINT [CK_KVK_CampMap_CampID]
