SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ID#]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ID#](
	[GovernorID] [float] NOT NULL
) ON [PRIMARY]
END
