SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[POWERDelta]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[POWERDelta](
	[GovernorID] [float] NOT NULL,
	[DeltaOrder] [float] NOT NULL,
	[Power_Delta] [float] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[POWERDelta]') AND name = N'IX_PowerDelta_DeltaOrder')
CREATE NONCLUSTERED INDEX [IX_PowerDelta_DeltaOrder] ON [dbo].[POWERDelta]
(
	[DeltaOrder] ASC
)
INCLUDE([GovernorID],[Power_Delta]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
