SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[D12]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[D12](
	[GovernorID] [float] NOT NULL,
	[DEADS] [float] NOT NULL,
	[ScanDate] [datetime] NOT NULL,
	[RowAsc12] [bigint] NULL,
	[RowDesc12] [bigint] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[D12]') AND name = N'IX_D12_GovernorID')
CREATE NONCLUSTERED INDEX [IX_D12_GovernorID] ON [dbo].[D12]
(
	[GovernorID] ASC
)
INCLUDE([DEADS],[RowAsc12],[RowDesc12]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
