SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NAMEFIX]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[NAMEFIX](
	[GI1] [float] NOT NULL,
	[GN1] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[GN2] [nchar](255) COLLATE Latin1_General_CI_AS NULL,
	[GN3] [nchar](255) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
END
