SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RALLY_STARTED_TABLE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RALLY_STARTED_TABLE](
	[GovernorID] [float] NOT NULL,
	[RALLY_STARTED] [int] NULL
) ON [PRIMARY]
END
