SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ProcConfig]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ProcConfig](
	[KVKVersion] [int] NOT NULL,
	[ConfigKey] [varchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[ConfigValue] [float] NULL,
	[LastUpdated] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[KVKVersion] ASC,
	[ConfigKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
SET ANSI_PADDING ON

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ProcConfig]') AND name = N'IX_ProcConfig_ConfigKey_KVKVersion')
CREATE NONCLUSTERED INDEX [IX_ProcConfig_ConfigKey_KVKVersion] ON [dbo].[ProcConfig]
(
	[ConfigKey] ASC,
	[KVKVersion] ASC
)
INCLUDE([ConfigValue]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ProcConfig]') AND name = N'IX_ProcConfig_Key')
CREATE NONCLUSTERED INDEX [IX_ProcConfig_Key] ON [dbo].[ProcConfig]
(
	[ConfigKey] ASC
)
INCLUDE([ConfigValue]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ProcConfig]') AND name = N'IX_ProcConfig_VK_Key')
CREATE NONCLUSTERED INDEX [IX_ProcConfig_VK_Key] ON [dbo].[ProcConfig]
(
	[KVKVersion] ASC,
	[ConfigKey] ASC
)
INCLUDE([ConfigValue]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
