SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PreKvk_Phases]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PreKvk_Phases](
	[KVK_NO] [int] NOT NULL,
	[Phase] [tinyint] NOT NULL,
	[PhaseName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[StartUTC] [datetime2](0) NOT NULL,
	[EndUTC] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_PreKvk_Phases] PRIMARY KEY CLUSTERED 
(
	[KVK_NO] ASC,
	[Phase] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
