-- S2A synthetic integration harness. AUTHORING ONLY until a disposable target is authorized.
-- Run the reviewed migration separately in an explicitly approved empty disposable database.
-- The caller must set session context KVK_S2A_AUTHORIZED_SERVER and KVK_S2A_AUTHORIZED_DATABASE
-- to that exact approved server/database, and KVK_S2A_DISPOSABLE_AUTHORIZED to integer 1.
-- No targets are supplied here; no SQLCMD substitutions, guessed hosts, USE, or connection defaults.
-- Disposable database name must start K98_S2A_Disposable_ (literal underscores).
-- This is a fixture rollback, not migration rollback. It cannot prove concurrent DAL locking,
-- commit-time completeness, immutable-write policy, parser admission or restart behavior.
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
IF @@TRANCOUNT <> 0
    THROW 51100, 'Constraint harness refuses an ambient transaction.', 1;
IF TRY_CONVERT(int, SESSION_CONTEXT(N'KVK_S2A_DISPOSABLE_AUTHORIZED')) IS NULL
   OR TRY_CONVERT(int, SESSION_CONTEXT(N'KVK_S2A_DISPOSABLE_AUTHORIZED')) <> 1
   OR CONVERT(nvarchar(128), SESSION_CONTEXT(N'KVK_S2A_AUTHORIZED_SERVER')) IS NULL
   OR CONVERT(nvarchar(128), SESSION_CONTEXT(N'KVK_S2A_AUTHORIZED_DATABASE')) IS NULL
   OR CONVERT(nvarchar(128), SESSION_CONTEXT(N'KVK_S2A_AUTHORIZED_SERVER')) COLLATE Latin1_General_100_BIN2 <> CONVERT(nvarchar(128), SERVERPROPERTY('ServerName')) COLLATE Latin1_General_100_BIN2
   OR CONVERT(nvarchar(128), SESSION_CONTEXT(N'KVK_S2A_AUTHORIZED_DATABASE')) COLLATE Latin1_General_100_BIN2 <> DB_NAME() COLLATE Latin1_General_100_BIN2
   OR DB_ID() <= 4 OR DB_NAME() NOT LIKE N'K98[_]S2A[_]Disposable[_]%'
    THROW 51100, 'Explicit authorization for this exact disposable server/database is required.', 1;

-- FK/check violations must remain recoverable at a savepoint in this test-only transaction.
-- Production DAL transaction policy is separate. Restore caller settings at the end.
DECLARE @WasXactAbort bit = CASE WHEN (16384 & @@OPTIONS) = 16384 THEN 1 ELSE 0 END;
DECLARE @WasRoundAbort bit = CASE WHEN (8192 & @@OPTIONS) = 8192 THEN 1 ELSE 0 END;
SET XACT_ABORT OFF;
SET NUMERIC_ROUNDABORT OFF;
DECLARE @obs uniqueidentifier = NEWID(), @obs2 uniqueidentifier = NEWID();
DECLARE @rev uniqueidentifier = NEWID(), @rev2 uniqueidentifier = NEWID();
DECLARE @report uniqueidentifier = NEWID(), @report2 uniqueidentifier = NEWID();
DECLARE @agg uniqueidentifier = NEWID(), @agg2 uniqueidentifier = NEWID();
DECLARE @roster uniqueidentifier = NEWID(), @attempt uniqueidentifier = NEWID();
DECLARE @hash binary(32) = HASHBYTES('SHA2_256', CONVERT(varbinary(16), NEWID()));
DECLARE @hash2 binary(32) = HASHBYTES('SHA2_256', CONVERT(varbinary(16), NEWID()));
DECLARE @utc datetime2(0) = '2000-01-01T00:00:00', @season int = 2147483600;
DECLARE @Passed int = 0;
BEGIN TRY
    BEGIN TRANSACTION;
    -- Refuse collisions rather than using or deleting any pre-existing source rows.
    IF EXISTS (SELECT 1 FROM KVK.SourceObservation WHERE KVK_NO = @season)
       OR EXISTS (SELECT 1 FROM KVK.SourceAggregateReport WHERE KVK_NO = @season)
        THROW 51100, 'Synthetic season already occupied; use an empty disposable target.', 1;

-- Valid graph across all twelve tables, including bigint extrema, genuine zero and unavailable B0.
INSERT KVK.SourceArtifact (ArtifactHash, ByteCount, StorageKey, CreatedUTC) VALUES (@hash, 100, LOWER(CONVERT(varchar(64), @hash, 2)) + N'.xlsx', @utc);
INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (@obs, 'snapshot_report_v1', @season, @utc, 'minute', N'main', NULL, 1);
INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson) VALUES (@rev, 'snapshot_report_v1', @season, @obs, 1, @hash, 'semantic_digest_v1', 'snapshot_report_players_v1', @hash, 'accepted', @utc, N'synthetic-operator', N'synthetic fixture', N'{}');
INSERT KVK.SourcePlayerSnapshot (RevisionID, SourceKey, KVK_NO, GovernorID, kingdom, name, power, dead, FieldStatusJson, RawProfileJson) VALUES (@rev, 'snapshot_report_v1', @season, 9223372036854775807, 1, N'Synthetic governor', 0, 9223372036854775807, N'{"power":"available","city_hall":"invalid_source_value","vip":"invalid_source_value","t1_kills":"invalid_source_value","t2_kills":"invalid_source_value","t3_kills":"invalid_source_value","t4_kills":"invalid_source_value","t5_kills":"invalid_source_value","total_kill_points":"invalid_source_value","ranged_points":"invalid_source_value","dead":"available","healed":"invalid_source_value","rss_assistance":"invalid_source_value","alliance_helps":"invalid_source_value","rss_gathered":"invalid_source_value","troops_power":"invalid_source_value","tech_power":"invalid_source_value","building_power":"invalid_source_value","commander_power":"invalid_source_value","kvk_played":"invalid_source_value","autarch_times":"invalid_source_value","most_kvk_kill":"invalid_source_value","most_kvk_dead":"invalid_source_value","most_kvk_heal":"invalid_source_value","acclaim":"invalid_source_value","highest_acclaim":"invalid_source_value","aoo_joined":"invalid_source_value","aoo_won":"invalid_source_value","aoo_avg_kill":"invalid_source_value","aoo_avg_dead":"invalid_source_value","aoo_avg_heal":"invalid_source_value"}', N'{}');
INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES ('snapshot_report_v1', @season, 10, @obs, @utc);
INSERT KVK.SourceRoster (RosterID, SourceKey, KVK_NO, RosterVersion, B0RevisionID, ScopeDigest, MemberDigest, MemberCount, ApprovedUTC, ApprovedBy, Reason, ProvenanceJson) VALUES (@roster, 'snapshot_report_v1', @season, 1, @rev, @hash, @hash, 1, @utc, N'synthetic-operator', N'approved B0 fixture', N'{}');
INSERT KVK.SourceRosterMember (RosterID, SourceKey, KVK_NO, GovernorID, b0_kingdom, b0_power) VALUES (@roster, 'snapshot_report_v1', @season, 9223372036854775807, 1, NULL);
INSERT KVK.SourceAggregateReport (ReportID, SourceKey, KVK_NO, PeriodKey, PeriodKind, SelectedRevisionID, SelectionVersion) VALUES (@report, 'snapshot_report_v1', @season, 'fight:synthetic', 'fight', NULL, 1);
INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson) VALUES (@agg, 'snapshot_report_v1', @season, @report, 'fight', 1, @hash, @hash, 'semantic_digest_v1', 'snapshot_report_aggregate_v1', @utc, 'minute', @utc, @utc, @utc, 'live', @utc, N'synthetic-operator', N'synthetic fixture', @hash, @hash, N'{}');
INSERT KVK.SourceImportAttempt (AttemptID, SourceKey, KVK_NO, GuildID, MessageID, AttachmentID, ActionKey, ArtifactHash, ActorID, ChannelID, OriginalFilename, ReceivedUTC, Status, DiagnosticSummary, ObservationRevisionID, ProvenanceJson) VALUES (@attempt, 'snapshot_report_v1', @season, 'synthetic-guild', 'synthetic-message', 'synthetic-attachment', 'accept', @hash, N'synthetic-operator', 'synthetic-channel', N'synthetic.xlsx', @utc, 'accepted', N'fixture accepted', @rev, N'{}');
INSERT KVK.SourceKingdomReportRow (RevisionID, SourceKey, KVK_NO, Kingdom, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@agg, 'snapshot_report_v1', @season, 1, 1, N'Synthetic camp', @hash, 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', N'{}');
INSERT KVK.SourceCampReportRow (RevisionID, SourceKey, KVK_NO, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@agg, 'snapshot_report_v1', @season, 1, N'Synthetic camp', @hash, 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', N'{}');
INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (@obs2, 'snapshot_report_v1', @season, DATEADD(minute, 1, @utc), 'minute', N'main', NULL, 1);
INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson) VALUES (@rev2, 'snapshot_report_v1', @season, @obs2, 1, @hash, 'semantic_digest_v1', 'snapshot_report_players_v1', @hash, 'accepted', @utc, N'synthetic-operator', N'synthetic fixture', N'{}');
INSERT KVK.SourceAggregateReport (ReportID, SourceKey, KVK_NO, PeriodKey, PeriodKind, SelectedRevisionID, SelectionVersion) VALUES (@report2, 'snapshot_report_v1', @season, 'overall', 'overall', NULL, 1);
INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson) VALUES (@agg2, 'snapshot_report_v1', @season, @report2, 'overall', 1, @hash, @hash, 'semantic_digest_v1', 'snapshot_report_aggregate_v1', @utc, 'minute', @utc, @utc, @utc, 'final', @utc, N'synthetic-operator', N'synthetic fixture', @hash, @hash, N'{}');
UPDATE KVK.SourceObservation SET SelectedRevisionID = @rev WHERE ObservationID = @obs;
UPDATE KVK.SourceAggregateReport SET SelectedRevisionID = @agg WHERE ReportID = @report;

-- Equivalent bytes can have a separate artifact/attempt while retaining the exact revision/scan.
INSERT KVK.SourceArtifact (ArtifactHash, ByteCount, StorageKey, CreatedUTC) VALUES (@hash2, 100, LOWER(CONVERT(varchar(64), @hash2, 2)) + N'.xlsx', @utc);
INSERT KVK.SourceImportAttempt (AttemptID, SourceKey, KVK_NO, GuildID, MessageID, AttachmentID, ActionKey, ArtifactHash, ActorID, ChannelID, OriginalFilename, ReceivedUTC, Status, DiagnosticSummary, ObservationRevisionID, ProvenanceJson) VALUES (NEWID(), 'snapshot_report_v1', @season, 'synthetic-guild', 'synthetic-message', 'synthetic-reexport', 'accept', @hash2, N'synthetic-operator', 'synthetic-channel', N'synthetic.xlsx', @utc, 'duplicate', N'fixture accepted', @rev, N'{}');
IF (SELECT COUNT(*) FROM KVK.SourceLogicalScan WHERE KVK_NO = @season) <> 1
    THROW 51100, 'Alias or aggregate allocated a player scan.', 1;
IF (SELECT COUNT(*) FROM KVK.SourceObservationRevision WHERE ObservationID = @obs) <> 1
    THROW 51100, 'Alias allocated another observation revision.', 1;
-- A finalization event may pin unchanged aggregate content; its hash must not suppress finality.
INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson, SupersedesRevisionID) VALUES (NEWID(), 'snapshot_report_v1', @season, @report, 'fight', 2, @hash, @hash, 'semantic_digest_v1', 'snapshot_report_aggregate_v1', @utc, 'minute', @utc, @utc, @utc, 'final', @utc, N'synthetic-operator', N'synthetic fixture', @hash, @hash, N'{}', @agg);

DECLARE @Cases TABLE (CaseNo int IDENTITY PRIMARY KEY, Label nvarchar(128), Statement nvarchar(max), ExpectedError int, ExpectedConstraint nvarchar(128));
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceArtifact', N'INSERT KVK.SourceArtifact (ArtifactHash, ByteCount, StorageKey, CreatedUTC) VALUES (@hash, 100, LOWER(CONVERT(varchar(64), @hash, 2)) + N''.xlsx'', @utc);', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceObservation', N'INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (@obs, ''snapshot_report_v1'', @season, @utc, ''minute'', N''main'', NULL, 1);', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceObservationRevision', N'INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson) VALUES (@rev, ''snapshot_report_v1'', @season, @obs, 1, @hash, ''semantic_digest_v1'', ''snapshot_report_players_v1'', @hash, ''accepted'', @utc, N''synthetic-operator'', N''synthetic fixture'', N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourcePlayerSnapshot', N'INSERT KVK.SourcePlayerSnapshot (RevisionID, SourceKey, KVK_NO, GovernorID, kingdom, name, power, dead, FieldStatusJson, RawProfileJson) VALUES (@rev, ''snapshot_report_v1'', @season, 9223372036854775807, 1, N''Synthetic governor'', 0, 9223372036854775807, N''{"power":"available","city_hall":"invalid_source_value","vip":"invalid_source_value","t1_kills":"invalid_source_value","t2_kills":"invalid_source_value","t3_kills":"invalid_source_value","t4_kills":"invalid_source_value","t5_kills":"invalid_source_value","total_kill_points":"invalid_source_value","ranged_points":"invalid_source_value","dead":"available","healed":"invalid_source_value","rss_assistance":"invalid_source_value","alliance_helps":"invalid_source_value","rss_gathered":"invalid_source_value","troops_power":"invalid_source_value","tech_power":"invalid_source_value","building_power":"invalid_source_value","commander_power":"invalid_source_value","kvk_played":"invalid_source_value","autarch_times":"invalid_source_value","most_kvk_kill":"invalid_source_value","most_kvk_dead":"invalid_source_value","most_kvk_heal":"invalid_source_value","acclaim":"invalid_source_value","highest_acclaim":"invalid_source_value","aoo_joined":"invalid_source_value","aoo_won":"invalid_source_value","aoo_avg_kill":"invalid_source_value","aoo_avg_dead":"invalid_source_value","aoo_avg_heal":"invalid_source_value"}'', N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceLogicalScan', N'INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES (''snapshot_report_v1'', @season, 10, @obs, @utc);', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceRoster', N'INSERT KVK.SourceRoster (RosterID, SourceKey, KVK_NO, RosterVersion, B0RevisionID, ScopeDigest, MemberDigest, MemberCount, ApprovedUTC, ApprovedBy, Reason, ProvenanceJson) VALUES (@roster, ''snapshot_report_v1'', @season, 1, @rev, @hash, @hash, 1, @utc, N''synthetic-operator'', N''approved B0 fixture'', N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceRosterMember', N'INSERT KVK.SourceRosterMember (RosterID, SourceKey, KVK_NO, GovernorID, b0_kingdom, b0_power) VALUES (@roster, ''snapshot_report_v1'', @season, 9223372036854775807, 1, NULL);', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceAggregateReport', N'INSERT KVK.SourceAggregateReport (ReportID, SourceKey, KVK_NO, PeriodKey, PeriodKind, SelectedRevisionID, SelectionVersion) VALUES (@report, ''snapshot_report_v1'', @season, ''fight:synthetic'', ''fight'', NULL, 1);', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceAggregateRevision', N'INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson) VALUES (@agg, ''snapshot_report_v1'', @season, @report, ''fight'', 1, @hash, @hash, ''semantic_digest_v1'', ''snapshot_report_aggregate_v1'', @utc, ''minute'', @utc, @utc, @utc, ''live'', @utc, N''synthetic-operator'', N''synthetic fixture'', @hash, @hash, N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceImportAttempt', N'INSERT KVK.SourceImportAttempt (AttemptID, SourceKey, KVK_NO, GuildID, MessageID, AttachmentID, ActionKey, ArtifactHash, ActorID, ChannelID, OriginalFilename, ReceivedUTC, Status, DiagnosticSummary, ObservationRevisionID, ProvenanceJson) VALUES (@attempt, ''snapshot_report_v1'', @season, ''synthetic-guild'', ''synthetic-message'', ''synthetic-attachment'', ''accept'', @hash, N''synthetic-operator'', ''synthetic-channel'', N''synthetic.xlsx'', @utc, ''accepted'', N''fixture accepted'', @rev, N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceKingdomReportRow', N'INSERT KVK.SourceKingdomReportRow (RevisionID, SourceKey, KVK_NO, Kingdom, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@agg, ''snapshot_report_v1'', @season, 1, 1, N''Synthetic camp'', @hash, 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'duplicate primary key SourceCampReportRow', N'INSERT KVK.SourceCampReportRow (RevisionID, SourceKey, KVK_NO, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@agg, ''snapshot_report_v1'', @season, 1, N''Synthetic camp'', @hash, 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', N''{}'');', 2627, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'event natural identity', N'INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''snapshot_report_v1'', @season, @utc, ''minute'', N''main'', NULL, 1);', 2627, N'UQ_SourceObservation_Event');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'replay identity', N'INSERT KVK.SourceImportAttempt (AttemptID, SourceKey, KVK_NO, GuildID, MessageID, AttachmentID, ActionKey, ArtifactHash, ActorID, ChannelID, OriginalFilename, ReceivedUTC, Status, DiagnosticSummary, ObservationRevisionID, ProvenanceJson) VALUES (NEWID(), ''snapshot_report_v1'', @season, ''synthetic-guild'', ''synthetic-message'', ''synthetic-attachment'', ''accept'', @hash, N''synthetic-operator'', ''synthetic-channel'', N''synthetic.xlsx'', @utc, ''accepted'', N''fixture accepted'', @rev, N''{}'');', 2627, N'UQ_SourceImportAttempt_Replay');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'semantic reexport must reuse observation revision', N'INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson) VALUES (NEWID(), ''snapshot_report_v1'', @season, @obs, 3, @hash, ''semantic_digest_v1'', ''snapshot_report_players_v1'', @hash, ''accepted'', @utc, N''synthetic-operator'', N''synthetic fixture'', N''{}'');', 2627, N'UQ_SourceObservationRevision_Digest');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'observation revision number', N'INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson) VALUES (NEWID(), ''snapshot_report_v1'', @season, @obs, 1, @hash2, ''semantic_digest_v1'', ''snapshot_report_players_v1'', @hash, ''accepted'', @utc, N''synthetic-operator'', N''synthetic fixture'', N''{}'');', 2627, N'UQ_SourceObservationRevision_Number');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'aggregate revision number', N'INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson) VALUES (NEWID(), ''snapshot_report_v1'', @season, @report, ''fight'', 1, @hash, @hash, ''semantic_digest_v1'', ''snapshot_report_aggregate_v1'', @utc, ''minute'', @utc, @utc, @utc, ''live'', @utc, N''synthetic-operator'', N''synthetic fixture'', @hash, @hash, N''{}'');', 2627, N'UQ_SourceAggregateRevision_Number');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'roster version', N'INSERT KVK.SourceRoster (RosterID, SourceKey, KVK_NO, RosterVersion, B0RevisionID, ScopeDigest, MemberDigest, MemberCount, ApprovedUTC, ApprovedBy, Reason, ProvenanceJson) VALUES (NEWID(), ''snapshot_report_v1'', @season, 1, @rev, @hash, @hash, 1, @utc, N''synthetic-operator'', N''approved B0 fixture'', N''{}'');', 2627, N'UQ_SourceRoster_Version');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'period natural identity', N'INSERT KVK.SourceAggregateReport (ReportID, SourceKey, KVK_NO, PeriodKey, PeriodKind, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''snapshot_report_v1'', @season, ''fight:synthetic'', ''fight'', NULL, 1);', 2627, N'UQ_SourceAggregateReport_Period');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'scan binding unique', N'INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES (''snapshot_report_v1'', @season, 11, @obs, @utc);', 2627, N'UQ_SourceLogicalScan_Observation');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'scan ID occupied', N'INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES (''snapshot_report_v1'', @season, 10, @obs2, @utc);', 2627, N'PK_SourceLogicalScan');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceObservationRevision', N'INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson) VALUES (NEWID(), ''snapshot_report_v1'', @season - 1, @obs, 9, @hash2, ''semantic_digest_v1'', ''snapshot_report_players_v1'', @hash, ''accepted'', @utc, N''synthetic-operator'', N''synthetic fixture'', N''{}'');', 547, N'FK_SourceObservationRevision_Observation');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourcePlayerSnapshot', N'INSERT KVK.SourcePlayerSnapshot (RevisionID, SourceKey, KVK_NO, GovernorID, kingdom, name, power, dead, FieldStatusJson, RawProfileJson) VALUES (@rev, ''snapshot_report_v1'', @season - 1, 2, 1, N''Synthetic governor'', 0, 9223372036854775807, N''{"power":"available","city_hall":"invalid_source_value","vip":"invalid_source_value","t1_kills":"invalid_source_value","t2_kills":"invalid_source_value","t3_kills":"invalid_source_value","t4_kills":"invalid_source_value","t5_kills":"invalid_source_value","total_kill_points":"invalid_source_value","ranged_points":"invalid_source_value","dead":"available","healed":"invalid_source_value","rss_assistance":"invalid_source_value","alliance_helps":"invalid_source_value","rss_gathered":"invalid_source_value","troops_power":"invalid_source_value","tech_power":"invalid_source_value","building_power":"invalid_source_value","commander_power":"invalid_source_value","kvk_played":"invalid_source_value","autarch_times":"invalid_source_value","most_kvk_kill":"invalid_source_value","most_kvk_dead":"invalid_source_value","most_kvk_heal":"invalid_source_value","acclaim":"invalid_source_value","highest_acclaim":"invalid_source_value","aoo_joined":"invalid_source_value","aoo_won":"invalid_source_value","aoo_avg_kill":"invalid_source_value","aoo_avg_dead":"invalid_source_value","aoo_avg_heal":"invalid_source_value"}'', N''{}'');', 547, N'FK_SourcePlayerSnapshot_Revision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceLogicalScan', N'INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES (''snapshot_report_v1'', @season - 1, 11, @obs, @utc);', 547, N'FK_SourceLogicalScan_Observation');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceRoster', N'INSERT KVK.SourceRoster (RosterID, SourceKey, KVK_NO, RosterVersion, B0RevisionID, ScopeDigest, MemberDigest, MemberCount, ApprovedUTC, ApprovedBy, Reason, ProvenanceJson) VALUES (NEWID(), ''snapshot_report_v1'', @season - 1, 1, @rev, @hash, @hash, 1, @utc, N''synthetic-operator'', N''approved B0 fixture'', N''{}'');', 547, N'FK_SourceRoster_B0');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceRosterMember', N'INSERT KVK.SourceRosterMember (RosterID, SourceKey, KVK_NO, GovernorID, b0_kingdom, b0_power) VALUES (@roster, ''snapshot_report_v1'', @season - 1, 2, 1, NULL);', 547, N'FK_SourceRosterMember_Roster');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceAggregateRevision', N'INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson) VALUES (NEWID(), ''snapshot_report_v1'', @season - 1, @report, ''fight'', 9, @hash, @hash, ''semantic_digest_v1'', ''snapshot_report_aggregate_v1'', @utc, ''minute'', @utc, @utc, @utc, ''live'', @utc, N''synthetic-operator'', N''synthetic fixture'', @hash, @hash, N''{}'');', 547, N'FK_SourceAggregateRevision_Report');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceKingdomReportRow', N'INSERT KVK.SourceKingdomReportRow (RevisionID, SourceKey, KVK_NO, Kingdom, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@agg, ''snapshot_report_v1'', @season - 1, 2, 1, N''Synthetic camp'', @hash, 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', N''{}'');', 547, N'FK_SourceKingdomReportRow_Revision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceCampReportRow', N'INSERT KVK.SourceCampReportRow (RevisionID, SourceKey, KVK_NO, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@agg, ''snapshot_report_v1'', @season - 1, 2, N''Synthetic camp'', @hash, 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', 25300000, N''25.3M'', 100000, ''reported_abbreviated'', N''{}'');', 547, N'FK_SourceCampReportRow_Revision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'cross-season SourceImportAttempt', N'INSERT KVK.SourceImportAttempt (AttemptID, SourceKey, KVK_NO, GuildID, MessageID, AttachmentID, ActionKey, ArtifactHash, ActorID, ChannelID, OriginalFilename, ReceivedUTC, Status, DiagnosticSummary, ObservationRevisionID, ProvenanceJson) VALUES (NEWID(), ''snapshot_report_v1'', @season - 1, ''synthetic-guild'', ''synthetic-message'', ''other'', ''accept'', @hash, N''synthetic-operator'', ''synthetic-channel'', N''synthetic.xlsx'', @utc, ''accepted'', N''fixture accepted'', @rev, N''{}'');', 547, N'FK_SourceImportAttempt_ObservationRevision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'selected revision belongs to another observation', N'UPDATE KVK.SourceObservation SET SelectedRevisionID = @rev2 WHERE ObservationID = @obs;', 547, N'FK_SourceObservation_SelectedRevision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'selected revision belongs to another report', N'UPDATE KVK.SourceAggregateReport SET SelectedRevisionID = @agg2 WHERE ReportID = @report;', 547, N'FK_SourceAggregateReport_SelectedRevision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'supersedes revision belongs to another observation', N'INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson, SupersedesRevisionID) VALUES (NEWID(), ''snapshot_report_v1'', @season, @obs, 9, @hash2, ''semantic_digest_v1'', ''snapshot_report_players_v1'', @hash, ''accepted'', @utc, N''synthetic-operator'', N''synthetic fixture'', N''{}'', @rev2);', 547, N'FK_SourceObservationRevision_Supersedes');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'supersedes revision belongs to another report', N'INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson, SupersedesRevisionID) VALUES (NEWID(), ''snapshot_report_v1'', @season, @report, ''fight'', 9, @hash, @hash, ''semantic_digest_v1'', ''snapshot_report_aggregate_v1'', @utc, ''minute'', @utc, @utc, @utc, ''live'', @utc, N''synthetic-operator'', N''synthetic fixture'', @hash, @hash, N''{}'', @agg2);', 547, N'FK_SourceAggregateRevision_Supersedes');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'wrong source allowlist', N'INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''legacy_full_data'', @season, @utc, ''minute'', N''main'', NULL, 1);', 547, N'CK_SourceObservation_Scope');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'source case sensitive', N'INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''SNAPSHOT_REPORT_V1'', @season, @utc, ''minute'', N''main'', NULL, 1);', 547, N'CK_SourceObservation_Scope');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero season', N'INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''snapshot_report_v1'', 0, @utc, ''minute'', N''main'', NULL, 1);', 547, N'CK_SourceObservation_Scope');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'minute precision cannot conceal seconds', N'INSERT KVK.SourceObservation (ObservationID, SourceKey, KVK_NO, ScanStartUTC, TimePrecision, EventDiscriminator, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''snapshot_report_v1'', @season, DATEADD(second, 1, @utc), ''minute'', N''main'', NULL, 1);', 547, N'CK_SourceObservation_Time');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero selection version', N'UPDATE KVK.SourceObservation SET SelectionVersion = 0 WHERE ObservationID = @obs;', 547, N'CK_SourceObservation_Selection');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero governor', N'INSERT KVK.SourcePlayerSnapshot (RevisionID, SourceKey, KVK_NO, GovernorID, kingdom, name, power, dead, FieldStatusJson, RawProfileJson) VALUES (@rev, ''snapshot_report_v1'', @season, 0, 1, N''Synthetic governor'', 0, 9223372036854775807, N''{"power":"available","city_hall":"invalid_source_value","vip":"invalid_source_value","t1_kills":"invalid_source_value","t2_kills":"invalid_source_value","t3_kills":"invalid_source_value","t4_kills":"invalid_source_value","t5_kills":"invalid_source_value","total_kill_points":"invalid_source_value","ranged_points":"invalid_source_value","dead":"available","healed":"invalid_source_value","rss_assistance":"invalid_source_value","alliance_helps":"invalid_source_value","rss_gathered":"invalid_source_value","troops_power":"invalid_source_value","tech_power":"invalid_source_value","building_power":"invalid_source_value","commander_power":"invalid_source_value","kvk_played":"invalid_source_value","autarch_times":"invalid_source_value","most_kvk_kill":"invalid_source_value","most_kvk_dead":"invalid_source_value","most_kvk_heal":"invalid_source_value","acclaim":"invalid_source_value","highest_acclaim":"invalid_source_value","aoo_joined":"invalid_source_value","aoo_won":"invalid_source_value","aoo_avg_kill":"invalid_source_value","aoo_avg_dead":"invalid_source_value","aoo_avg_heal":"invalid_source_value"}'', N''{}'');', 547, N'CK_SourcePlayerSnapshot_Identity');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative governor', N'INSERT KVK.SourcePlayerSnapshot (RevisionID, SourceKey, KVK_NO, GovernorID, kingdom, name, power, dead, FieldStatusJson, RawProfileJson) VALUES (@rev, ''snapshot_report_v1'', @season, -1, 1, N''Synthetic governor'', 0, 9223372036854775807, N''{"power":"available","city_hall":"invalid_source_value","vip":"invalid_source_value","t1_kills":"invalid_source_value","t2_kills":"invalid_source_value","t3_kills":"invalid_source_value","t4_kills":"invalid_source_value","t5_kills":"invalid_source_value","total_kill_points":"invalid_source_value","ranged_points":"invalid_source_value","dead":"available","healed":"invalid_source_value","rss_assistance":"invalid_source_value","alliance_helps":"invalid_source_value","rss_gathered":"invalid_source_value","troops_power":"invalid_source_value","tech_power":"invalid_source_value","building_power":"invalid_source_value","commander_power":"invalid_source_value","kvk_played":"invalid_source_value","autarch_times":"invalid_source_value","most_kvk_kill":"invalid_source_value","most_kvk_dead":"invalid_source_value","most_kvk_heal":"invalid_source_value","acclaim":"invalid_source_value","highest_acclaim":"invalid_source_value","aoo_joined":"invalid_source_value","aoo_won":"invalid_source_value","aoo_avg_kill":"invalid_source_value","aoo_avg_dead":"invalid_source_value","aoo_avg_heal":"invalid_source_value"}'', N''{}'');', 547, N'CK_SourcePlayerSnapshot_Identity');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero scan ID', N'INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES (''snapshot_report_v1'', @season, 0, @obs2, @utc);', 547, N'CK_SourceLogicalScan_ID');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'scan int overflow', N'INSERT KVK.SourceLogicalScan (SourceKey, KVK_NO, LogicalScanID, ObservationID, AllocatedUTC) VALUES (''snapshot_report_v1'', @season, 2147483648, @obs2, @utc);', 8115, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'governor bigint overflow', N'INSERT KVK.SourcePlayerSnapshot (RevisionID, SourceKey, KVK_NO, GovernorID, kingdom, name, power, dead, FieldStatusJson, RawProfileJson) VALUES (@rev, ''snapshot_report_v1'', @season, 9223372036854775808, 1, N''Synthetic governor'', 0, 9223372036854775807, N''{"power":"available","city_hall":"invalid_source_value","vip":"invalid_source_value","t1_kills":"invalid_source_value","t2_kills":"invalid_source_value","t3_kills":"invalid_source_value","t4_kills":"invalid_source_value","t5_kills":"invalid_source_value","total_kill_points":"invalid_source_value","ranged_points":"invalid_source_value","dead":"available","healed":"invalid_source_value","rss_assistance":"invalid_source_value","alliance_helps":"invalid_source_value","rss_gathered":"invalid_source_value","troops_power":"invalid_source_value","tech_power":"invalid_source_value","building_power":"invalid_source_value","commander_power":"invalid_source_value","kvk_played":"invalid_source_value","autarch_times":"invalid_source_value","most_kvk_kill":"invalid_source_value","most_kvk_dead":"invalid_source_value","most_kvk_heal":"invalid_source_value","acclaim":"invalid_source_value","highest_acclaim":"invalid_source_value","aoo_joined":"invalid_source_value","aoo_won":"invalid_source_value","aoo_avg_kill":"invalid_source_value","aoo_avg_dead":"invalid_source_value","aoo_avg_heal":"invalid_source_value"}'', N''{}'');', 8115, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative player counter', N'UPDATE KVK.SourcePlayerSnapshot SET dead = -1 WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'unavailable must not become zero', N'UPDATE KVK.SourcePlayerSnapshot SET t4_kills = 0 WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_t4_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'available cannot become null', N'UPDATE KVK.SourcePlayerSnapshot SET power = NULL WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_power');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'missing field status', N'UPDATE KVK.SourcePlayerSnapshot SET FieldStatusJson = N''{}'' WHERE RevisionID = @rev;', 547, N'');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'generated storage key only', N'INSERT KVK.SourceArtifact (ArtifactHash, ByteCount, StorageKey, CreatedUTC) VALUES (HASHBYTES(''SHA2_256'', 0x01), 100, N''../synthetic.xlsx'', @utc);', 547, N'CK_SourceArtifact_Storage');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero artifact bytes', N'UPDATE KVK.SourceArtifact SET ByteCount = 0 WHERE ArtifactHash = @hash;', 547, N'CK_SourceArtifact_Bytes');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'artifact byte limit', N'UPDATE KVK.SourceArtifact SET ByteCount = 20971521 WHERE ArtifactHash = @hash;', 547, N'CK_SourceArtifact_Bytes');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'accepted attempt requires one exact result', N'UPDATE KVK.SourceImportAttempt SET ObservationRevisionID = NULL WHERE AttemptID = @attempt;', 547, N'CK_SourceImportAttempt_Result');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'attempt cannot bind both streams', N'UPDATE KVK.SourceImportAttempt SET AggregateRevisionID = @agg WHERE AttemptID = @attempt;', 547, N'CK_SourceImportAttempt_Result');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'aggregate mapping provenance', N'UPDATE KVK.SourceKingdomReportRow SET MappingDigest = @hash2 WHERE RevisionID = @agg;', 547, N'FK_SourceKingdomReportRow_Revision');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'camp out of range', N'UPDATE KVK.SourceCampReportRow SET CampID = 9 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_Identity');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'reversed aggregate coverage', N'UPDATE KVK.SourceAggregateRevision SET CoverageEndUTC = DATEADD(second,-1,@utc) WHERE RevisionID = @agg;', 547, N'CK_SourceAggregateRevision_Time');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'overall cannot accept live', N'UPDATE KVK.SourceAggregateRevision SET ReportState = ''live'' WHERE RevisionID = @agg2;', 547, N'CK_SourceAggregateRevision_State');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'no-fight aggregate rejects', N'INSERT KVK.SourceAggregateReport (ReportID, SourceKey, KVK_NO, PeriodKey, PeriodKind, SelectedRevisionID, SelectionVersion) VALUES (NEWID(), ''snapshot_report_v1'', @season, ''no_fight:synthetic'', ''no_fight'', NULL, 1);', 547, N'CK_SourceAggregateReport_Period');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow t4_kills', N'UPDATE KVK.SourceKingdomReportRow SET t4_kills = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_t4_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow t4_kills', N'UPDATE KVK.SourceKingdomReportRow SET t4_kills_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_t4_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow t5_kills', N'UPDATE KVK.SourceKingdomReportRow SET t5_kills = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_t5_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow t5_kills', N'UPDATE KVK.SourceKingdomReportRow SET t5_kills_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_t5_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow kp_t4_t5', N'UPDATE KVK.SourceKingdomReportRow SET kp_t4_t5 = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_kp_t4_t5');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow kp_t4_t5', N'UPDATE KVK.SourceKingdomReportRow SET kp_t4_t5_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_kp_t4_t5');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow dead', N'UPDATE KVK.SourceKingdomReportRow SET dead = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow dead', N'UPDATE KVK.SourceKingdomReportRow SET dead_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow t4_t5_dead', N'UPDATE KVK.SourceKingdomReportRow SET t4_t5_dead = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_t4_t5_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow t4_t5_dead', N'UPDATE KVK.SourceKingdomReportRow SET t4_t5_dead_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_t4_t5_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow healed', N'UPDATE KVK.SourceKingdomReportRow SET healed = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_healed');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow healed', N'UPDATE KVK.SourceKingdomReportRow SET healed_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_healed');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow acclaim', N'UPDATE KVK.SourceKingdomReportRow SET acclaim = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_acclaim');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow acclaim', N'UPDATE KVK.SourceKingdomReportRow SET acclaim_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_acclaim');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceKingdomReportRow dkp', N'UPDATE KVK.SourceKingdomReportRow SET dkp = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_dkp');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceKingdomReportRow dkp', N'UPDATE KVK.SourceKingdomReportRow SET dkp_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceKingdomReportRow_dkp');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow t4_kills', N'UPDATE KVK.SourceCampReportRow SET t4_kills = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_t4_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow t4_kills', N'UPDATE KVK.SourceCampReportRow SET t4_kills_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_t4_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow t5_kills', N'UPDATE KVK.SourceCampReportRow SET t5_kills = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_t5_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow t5_kills', N'UPDATE KVK.SourceCampReportRow SET t5_kills_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_t5_kills');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow kp_t4_t5', N'UPDATE KVK.SourceCampReportRow SET kp_t4_t5 = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_kp_t4_t5');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow kp_t4_t5', N'UPDATE KVK.SourceCampReportRow SET kp_t4_t5_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_kp_t4_t5');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow dead', N'UPDATE KVK.SourceCampReportRow SET dead = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow dead', N'UPDATE KVK.SourceCampReportRow SET dead_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow t4_t5_dead', N'UPDATE KVK.SourceCampReportRow SET t4_t5_dead = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_t4_t5_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow t4_t5_dead', N'UPDATE KVK.SourceCampReportRow SET t4_t5_dead_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_t4_t5_dead');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow healed', N'UPDATE KVK.SourceCampReportRow SET healed = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_healed');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow healed', N'UPDATE KVK.SourceCampReportRow SET healed_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_healed');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow acclaim', N'UPDATE KVK.SourceCampReportRow SET acclaim = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_acclaim');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow acclaim', N'UPDATE KVK.SourceCampReportRow SET acclaim_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_acclaim');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'negative SourceCampReportRow dkp', N'UPDATE KVK.SourceCampReportRow SET dkp = -1 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_dkp');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'zero unit SourceCampReportRow dkp', N'UPDATE KVK.SourceCampReportRow SET dkp_unit = 0 WHERE RevisionID = @agg;', 547, N'CK_SourceCampReportRow_dkp');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'aggregate decimal overflow', N'UPDATE KVK.SourceCampReportRow SET dkp = 100000000000000000000000000000000 WHERE RevisionID = @agg;', 8115, N'');

INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'noncanonical field status Available', N'UPDATE KVK.SourcePlayerSnapshot SET FieldStatusJson = JSON_MODIFY(FieldStatusJson, ''$.power'', ''Available'') WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_power');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'noncanonical field status Invalid_source_value', N'UPDATE KVK.SourcePlayerSnapshot SET FieldStatusJson = JSON_MODIFY(FieldStatusJson, ''$.city_hall'', ''Invalid_source_value'') WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_city_hall');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'noncanonical field status Unsupported', N'UPDATE KVK.SourcePlayerSnapshot SET FieldStatusJson = JSON_MODIFY(FieldStatusJson, ''$.city_hall'', ''Unsupported'') WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_city_hall');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'noncanonical field status Not_applicable', N'UPDATE KVK.SourcePlayerSnapshot SET FieldStatusJson = JSON_MODIFY(FieldStatusJson, ''$.city_hall'', ''Not_applicable'') WHERE RevisionID = @rev;', 547, N'CK_SourcePlayerSnapshot_city_hall');
INSERT @Cases (Label, Statement, ExpectedError, ExpectedConstraint) VALUES (N'corrected observation requires predecessor', N'UPDATE KVK.SourceObservationRevision SET AcceptanceState = ''corrected'', SupersedesRevisionID = NULL WHERE RevisionID = @rev;', 547, N'CK_SourceObservationRevision_State');

DECLARE @CaseNo int = 1, @Label nvarchar(128), @Statement nvarchar(max), @ExpectedError int, @ExpectedConstraint nvarchar(128);
DECLARE @Rejected bit, @ActualError int, @ActualMessage nvarchar(4000);
WHILE @CaseNo <= (SELECT MAX(CaseNo) FROM @Cases)
BEGIN
    SELECT @Label = Label, @Statement = Statement, @ExpectedError = ExpectedError, @ExpectedConstraint = ExpectedConstraint FROM @Cases WHERE CaseNo = @CaseNo;
    SET @Rejected = 0;
    SAVE TRANSACTION RejectionCase;
    BEGIN TRY
        EXEC sys.sp_executesql @Statement,
          N'@obs uniqueidentifier,@obs2 uniqueidentifier,@rev uniqueidentifier,@rev2 uniqueidentifier,@report uniqueidentifier,@report2 uniqueidentifier,@agg uniqueidentifier,@agg2 uniqueidentifier,@roster uniqueidentifier,@attempt uniqueidentifier,@hash binary(32),@hash2 binary(32),@utc datetime2(0),@season int',
          @obs,@obs2,@rev,@rev2,@report,@report2,@agg,@agg2,@roster,@attempt,@hash,@hash2,@utc,@season;
    END TRY
    BEGIN CATCH
        SET @ActualError = ERROR_NUMBER(); SET @ActualMessage = ERROR_MESSAGE();
        IF @ActualError <> @ExpectedError OR (@ExpectedConstraint <> N'' AND CHARINDEX(@ExpectedConstraint, @ActualMessage) = 0)
        BEGIN
            PRINT @Label;
            THROW;
        END;
        IF XACT_STATE() <> 1 THROW 51100, 'Expected rejection doomed the fixture transaction.', 1;
        SET @Rejected = 1;
    END CATCH;
    ROLLBACK TRANSACTION RejectionCase;
    IF @Rejected = 0
    BEGIN
        PRINT @Label;
        THROW 51100, 'Expected constraint rejection did not occur.', 1;
    END;
    SET @Passed += 1;
    SET @CaseNo += 1;
END;

-- Canonical enum tokens remain valid with the case-sensitive JSON value collation.
SAVE TRANSACTION CanonicalStates;
UPDATE KVK.SourcePlayerSnapshot SET city_hall = NULL, FieldStatusJson = JSON_MODIFY(FieldStatusJson, '$.city_hall', 'unsupported') WHERE RevisionID = @rev;
UPDATE KVK.SourcePlayerSnapshot SET FieldStatusJson = JSON_MODIFY(FieldStatusJson, '$.city_hall', 'not_applicable') WHERE RevisionID = @rev;
ROLLBACK TRANSACTION CanonicalStates;
-- A corrected revision with a same-observation predecessor is accepted; undo it after proof.
SAVE TRANSACTION CorrectedLineage;
DECLARE @correction uniqueidentifier = NEWID();
INSERT KVK.SourceObservationRevision (RevisionID, SourceKey, KVK_NO, ObservationID, RevisionNo, SemanticHash, DigestVersion, SchemaVersion, ArtifactHash, SupersedesRevisionID, AcceptanceState, AcceptedUTC, AcceptedBy, Reason, MetadataJson)
VALUES (@correction, 'snapshot_report_v1', @season, @obs, 99, @hash2, 'semantic_digest_v1', 'snapshot_report_players_v1', @hash, @rev, 'corrected', @utc, N'synthetic-operator', N'correction with predecessor', N'{}');
IF NOT EXISTS (SELECT 1 FROM KVK.SourceObservationRevision WHERE RevisionID = @correction AND SupersedesRevisionID = @rev AND AcceptanceState = 'corrected')
    THROW 51100, 'Valid correction lineage was not stored.', 1;
ROLLBACK TRANSACTION CorrectedLineage;

-- Exact decimal boundary and raw/unit precision survive storage without binary float.
UPDATE KVK.SourceCampReportRow SET dkp = 99999999999999999999999999999999.999999 WHERE RevisionID = @agg;
IF NOT EXISTS (SELECT 1 FROM KVK.SourceCampReportRow WHERE RevisionID = @agg AND dkp = 99999999999999999999999999999999.999999 AND t4_kills_raw = N'25.3M' AND t4_kills_unit = 100000)
    THROW 51100, 'Exact aggregate precision did not survive storage.', 1;
-- T46 simulation: failure after only kingdom rows, before camp rows, rolls back the candidate.
SAVE TRANSACTION PartialAggregate;
INSERT KVK.SourceAggregateRevision (RevisionID, SourceKey, KVK_NO, ReportID, PeriodKind, RevisionNo, ArtifactHash, SemanticHash, DigestVersion, SchemaVersion, ScanStartUTC, TimePrecision, CoverageStartUTC, CoverageEndUTC, AsOfUTC, ReportState, AcceptedUTC, AcceptedBy, Reason, MappingDigest, ScopeDigest, MetadataJson) VALUES (@rev2, 'snapshot_report_v1', @season, @report, 'fight', 3, @hash, @hash, 'semantic_digest_v1', 'snapshot_report_aggregate_v1', @utc, 'minute', @utc, @utc, @utc, 'live', @utc, N'synthetic-operator', N'synthetic fixture', @hash, @hash, N'{}');
INSERT KVK.SourceKingdomReportRow (RevisionID, SourceKey, KVK_NO, Kingdom, CampID, CampLabel, MappingDigest, t4_kills, t4_kills_raw, t4_kills_unit, t4_kills_precision, t5_kills, t5_kills_raw, t5_kills_unit, t5_kills_precision, kp_t4_t5, kp_t4_t5_raw, kp_t4_t5_unit, kp_t4_t5_precision, dead, dead_raw, dead_unit, dead_precision, t4_t5_dead, t4_t5_dead_raw, t4_t5_dead_unit, t4_t5_dead_precision, healed, healed_raw, healed_unit, healed_precision, acclaim, acclaim_raw, acclaim_unit, acclaim_precision, dkp, dkp_raw, dkp_unit, dkp_precision, RawCellsJson) VALUES (@rev2, 'snapshot_report_v1', @season, 1, 1, N'Synthetic camp', @hash, 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', 25300000, N'25.3M', 100000, 'reported_abbreviated', N'{}');
ROLLBACK TRANSACTION PartialAggregate;
IF EXISTS (SELECT 1 FROM KVK.SourceAggregateRevision WHERE RevisionID = @rev2)
   OR EXISTS (SELECT 1 FROM KVK.SourceKingdomReportRow WHERE RevisionID = @rev2)
   OR EXISTS (SELECT 1 FROM KVK.SourceCampReportRow WHERE RevisionID = @rev2)
   OR NOT EXISTS (SELECT 1 FROM KVK.SourceAggregateReport WHERE ReportID = @report AND SelectedRevisionID = @agg)
    THROW 51100, 'Half aggregate survived rollback or changed selection.', 1;

ROLLBACK TRANSACTION;
IF @@TRANCOUNT <> 0 THROW 51100, 'Fixture transaction remained open.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceArtifact WHERE ArtifactHash IN (@hash, @hash2))
    THROW 51100, 'Synthetic rows survived rollback: SourceArtifact.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceImportAttempt WHERE ArtifactHash IN (@hash, @hash2))
    THROW 51100, 'Synthetic rows survived rollback: SourceImportAttempt.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceObservation WHERE ObservationID IN (@obs, @obs2))
    THROW 51100, 'Synthetic rows survived rollback: SourceObservation.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceObservationRevision WHERE RevisionID IN (@rev, @rev2))
    THROW 51100, 'Synthetic rows survived rollback: SourceObservationRevision.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourcePlayerSnapshot WHERE RevisionID IN (@rev))
    THROW 51100, 'Synthetic rows survived rollback: SourcePlayerSnapshot.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceLogicalScan WHERE ObservationID IN (@obs, @obs2))
    THROW 51100, 'Synthetic rows survived rollback: SourceLogicalScan.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceRoster WHERE RosterID IN (@roster))
    THROW 51100, 'Synthetic rows survived rollback: SourceRoster.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceRosterMember WHERE RosterID IN (@roster))
    THROW 51100, 'Synthetic rows survived rollback: SourceRosterMember.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceAggregateReport WHERE ReportID IN (@report, @report2))
    THROW 51100, 'Synthetic rows survived rollback: SourceAggregateReport.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceAggregateRevision WHERE ReportID IN (@report, @report2))
    THROW 51100, 'Synthetic rows survived rollback: SourceAggregateRevision.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceKingdomReportRow WHERE RevisionID IN (@agg, @rev2))
    THROW 51100, 'Synthetic rows survived rollback: SourceKingdomReportRow.', 1;
IF EXISTS (SELECT 1 FROM KVK.SourceCampReportRow WHERE RevisionID IN (@agg, @rev2))
    THROW 51100, 'Synthetic rows survived rollback: SourceCampReportRow.', 1;
IF @WasXactAbort = 1 SET XACT_ABORT ON;
IF @WasRoundAbort = 1 SET NUMERIC_ROUNDABORT ON;
SELECT @Passed AS ExpectedRejectionsPassed, 12 AS TablesCheckedForRollback, N'ROLLBACK verified; concurrency/DAL integration not tested' AS Outcome;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    IF @WasXactAbort = 1 SET XACT_ABORT ON;
    IF @WasRoundAbort = 1 SET NUMERIC_ROUNDABORT ON;
    THROW;
END CATCH;
